{
    "\u231a": " watch",
    "\u231b": " hourglass done",
    "\u23e9": " fast-forward button",
    "\u23ec": " fast down button",
    "\u23f0": " alarm clock",
    "\u23f3": " hourglass not done",
    "\u25fd": " white medium-small square",
    "\u25fe": " black medium-small square",
    "\u2614": " umbrella with rain drops",
    "\u2615": " hot beverage",
    "\u2648": " Aries",
    "\u2653": " Pisces",
    "\u267f": " wheelchair symbol",
    "\u2693": " anchor",
    "\u26a1": " high voltage",
    "\u26aa": " white circle",
    "\u26ab": " black circle",
    "\u26bd": " soccer ball",
    "\u26be": " baseball",
    "\u26c4": " snowman without snow",
    "\u26c5": " sun behind cloud",
    "\u26ce": " Ophiuchus",
    "\u26d4": " no entry",
    "\u26ea": " church",
    "\u26f2": " fountain",
    "\u26f3": " flag in hole",
    "\u26f5": " sailboat",
    "\u26fa": " tent",
    "\u26fd": " fuel pump",
    "\u2705": " check mark button",
    "\u270a": " raised fist",
    "\u270b": " raised hand",
    "\u2728": " sparkles",
    "\u274c": " cross mark",
    "\u274e": " cross mark button",
    "\u2753": " red question mark",
    "\u2755": " white exclamation mark",
    "\u2757": " red exclamation mark",
    "\u2795": " plus",
    "\u2797": " divide",
    "\u27b0": " curly loop",
    "\u27bf": " double curly loop",
    "\u2b1b": " black large square",
    "\u2b1c": " white large square",
    "\u2b50": " star",
    "\u2b55": " hollow red circle",
    "\ud83c\udc04": " mahjong red dragon",
    "\ud83c\udccf": " joker",
    "\ud83c\udd8e": " AB button (blood type)",
    "\ud83c\udd91": " CL button",
    "\ud83c\udd9a": " VS button",
    "\ud83c\ude01": " Japanese \u201chere\u201d button",
    "\ud83c\ude1a": " Japanese \u201cfree of charge\u201d button",
    "\ud83c\ude2f": " Japanese \u201creserved\u201d button",
    "\ud83c\ude32": " Japanese \u201cprohibited\u201d button",
    "\ud83c\ude36": " Japanese \u201cnot free of charge\u201d button",
    "\ud83c\ude38": " Japanese \u201capplication\u201d button",
    "\ud83c\ude3a": " Japanese \u201copen for business\u201d button",
    "\ud83c\ude50": " Japanese \u201cbargain\u201d button",
    "\ud83c\ude51": " Japanese \u201cacceptable\u201d button",
    "\ud83c\udf00": " cyclone",
    "\ud83c\udf0c": " milky way",
    "\ud83c\udf0d": " globe showing Europe-Africa",
    "\ud83c\udf0e": " globe showing Americas",
    "\ud83c\udf0f": " globe showing Asia-Australia",
    "\ud83c\udf10": " globe with meridians",
    "\ud83c\udf11": " new moon",
    "\ud83c\udf12": " waxing crescent moon",
    "\ud83c\udf13": " first quarter moon",
    "\ud83c\udf15": " full moon",
    "\ud83c\udf16": " waning gibbous moon",
    "\ud83c\udf18": " waning crescent moon",
    "\ud83c\udf19": " crescent moon",
    "\ud83c\udf1a": " new moon face",
    "\ud83c\udf1b": " first quarter moon face",
    "\ud83c\udf1c": " last quarter moon face",
    "\ud83c\udf1d": " full moon face",
    "\ud83c\udf1e": " sun with face",
    "\ud83c\udf1f": " glowing star",
    "\ud83c\udf20": " shooting star",
    "\ud83c\udf2d": " hot dog",
    "\ud83c\udf2f": " burrito",
    "\ud83c\udf30": " chestnut",
    "\ud83c\udf31": " seedling",
    "\ud83c\udf32": " evergreen tree",
    "\ud83c\udf33": " deciduous tree",
    "\ud83c\udf34": " palm tree",
    "\ud83c\udf35": " cactus",
    "\ud83c\udf37": " tulip",
    "\ud83c\udf4a": " tangerine",
    "\ud83c\udf4b": " lemon",
    "\ud83c\udf4c": " banana",
    "\ud83c\udf4f": " green apple",
    "\ud83c\udf50": " pear",
    "\ud83c\udf51": " peach",
    "\ud83c\udf7b": " clinking beer mugs",
    "\ud83c\udf7c": " baby bottle",
    "\ud83c\udf7e": " bottle with popping cork",
    "\ud83c\udf7f": " popcorn",
    "\ud83c\udf80": " ribbon",
    "\ud83c\udf93": " graduation cap",
    "\ud83c\udfa0": " carousel horse",
    "\ud83c\udfc4": " person surfing",
    "\ud83c\udfc5": " sports medal",
    "\ud83c\udfc6": " trophy",
    "\ud83c\udfc7": " horse racing",
    "\ud83c\udfc8": " american football",
    "\ud83c\udfc9": " rugby football",
    "\ud83c\udfca": " person swimming",
    "\ud83c\udfcf": " cricket game",
    "\ud83c\udfd3": " ping pong",
    "\ud83c\udfe0": " house",
    "\ud83c\udfe3": " Japanese post office",
    "\ud83c\udfe4": " post office",
    "\ud83c\udfe5": " hospital",
    "\ud83c\udff0": " castle",
    "\ud83c\udff4": " black flag",
    "\ud83c\udff8": " badminton",
    "\ud83d\udc07": " rabbit",
    "\ud83d\udc08": " cat",
    "\ud83d\udc09": " dragon",
    "\ud83d\udc0b": " whale",
    "\ud83d\udc0c": " snail",
    "\ud83d\udc0e": " horse",
    "\ud83d\udc0f": " ram",
    "\ud83d\udc10": " goat",
    "\ud83d\udc11": " ewe",
    "\ud83d\udc12": " monkey",
    "\ud83d\udc13": " rooster",
    "\ud83d\udc14": " chicken",
    "\ud83d\udc15": " dog",
    "\ud83d\udc16": " pig",
    "\ud83d\udc17": " boar",
    "\ud83d\udc29": " poodle",
    "\ud83d\udc2a": " camel",
    "\ud83d\udc2b": " two-hump camel",
    "\ud83d\udc3e": " paw prints",
    "\ud83d\udc40": " eyes",
    "\ud83d\udc42": " ear",
    "\ud83d\udc64": " bust in silhouette",
    "\ud83d\udc65": " busts in silhouette",
    "\ud83d\udc66": " boy",
    "\ud83d\udc6b": " woman and man holding hands",
    "\ud83d\udc6c": " men holding hands",
    "\ud83d\udc6d": " women holding hands",
    "\ud83d\udc6e": " police officer",
    "\ud83d\udcac": " speech balloon",
    "\ud83d\udcad": " thought balloon",
    "\ud83d\udcae": " white flower",
    "\ud83d\udcb5": " dollar banknote",
    "\ud83d\udcb6": " euro banknote",
    "\ud83d\udcb7": " pound banknote",
    "\ud83d\udcb8": " money with wings",
    "\ud83d\udceb": " closed mailbox with raised flag",
    "\ud83d\udcec": " open mailbox with raised flag",
    "\ud83d\udced": " open mailbox with lowered flag",
    "\ud83d\udcee": " postbox",
    "\ud83d\udcef": " postal horn",
    "\ud83d\udcf0": " newspaper",
    "\ud83d\udcf4": " mobile phone off",
    "\ud83d\udcf5": " no mobile phones",
    "\ud83d\udcf6": " antenna bars",
    "\ud83d\udcf7": " camera",
    "\ud83d\udcf8": " camera with flash",
    "\ud83d\udcf9": " video camera",
    "\ud83d\udcfc": " videocassette",
    "\ud83d\udcff": " prayer beads",
    "\ud83d\udd02": " repeat single button",
    "\ud83d\udd03": " clockwise vertical arrows",
    "\ud83d\udd04": " counterclockwise arrows button",
    "\ud83d\udd07": " muted speaker",
    "\ud83d\udd08": " speaker low volume",
    "\ud83d\udd09": " speaker medium volume",
    "\ud83d\udd0a": " speaker high volume",
    "\ud83d\udd14": " bell",
    "\ud83d\udd15": " bell with slash",
    "\ud83d\udd16": " bookmark",
    "\ud83d\udd2b": " water pistol",
    "\ud83d\udd2c": " microscope",
    "\ud83d\udd2d": " telescope",
    "\ud83d\udd2e": " crystal ball",
    "\ud83d\udd3d": " downwards button",
    "\ud83d\udd4b": " kaaba",
    "\ud83d\udd4e": " menorah",
    "\ud83d\udd50": " one o\u2019clock",
    "\ud83d\udd5b": " twelve o\u2019clock",
    "\ud83d\udd5c": " one-thirty",
    "\ud83d\udd67": " twelve-thirty",
    "\ud83d\udd7a": " man dancing",
    "\ud83d\udd95": " middle finger",
    "\ud83d\udd96": " vulcan salute",
    "\ud83d\udda4": " black heart",
    "\ud83d\uddfb": " mount fuji",
    "\ud83d\uddff": " moai",
    "\ud83d\ude00": " grinning face",
    "\ud83d\ude01": " beaming face with smiling eyes",
    "\ud83d\ude06": " grinning squinting face",
    "\ud83d\ude07": " smiling face with halo",
    "\ud83d\ude08": " smiling face with horns",
    "\ud83d\ude09": " winking face",
    "\ud83d\ude0d": " smiling face with heart-eyes",
    "\ud83d\ude0e": " smiling face with sunglasses",
    "\ud83d\ude0f": " smirking face",
    "\ud83d\ude10": " neutral face",
    "\ud83d\ude11": " expressionless face",
    "\ud83d\ude12": " unamused face",
    "\ud83d\ude14": " pensive face",
    "\ud83d\ude15": " confused face",
    "\ud83d\ude16": " confounded face",
    "\ud83d\ude17": " kissing face",
    "\ud83d\ude18": " face blowing a kiss",
    "\ud83d\ude19": " kissing face with smiling eyes",
    "\ud83d\ude1a": " kissing face with closed eyes",
    "\ud83d\ude1b": " face with tongue",
    "\ud83d\ude1c": " winking face with tongue",
    "\ud83d\ude1e": " disappointed face",
    "\ud83d\ude1f": " worried face",
    "\ud83d\ude20": " angry face",
    "\ud83d\ude25": " sad but relieved face",
    "\ud83d\ude26": " frowning face with open mouth",
    "\ud83d\ude27": " anguished face",
    "\ud83d\ude28": " fearful face",
    "\ud83d\ude2b": " tired face",
    "\ud83d\ude2c": " grimacing face",
    "\ud83d\ude2d": " loudly crying face",
    "\ud83d\ude2e": " face with open mouth",
    "\ud83d\ude2f": " hushed face",
    "\ud83d\ude30": " anxious face with sweat",
    "\ud83d\ude33": " flushed face",
    "\ud83d\ude34": " sleeping face",
    "\ud83d\ude35": " face with crossed-out eyes",
    "\ud83d\ude36": " face without mouth",
    "\ud83d\ude37": " face with medical mask",
    "\ud83d\ude40": " weary cat",
    "\ud83d\ude41": " slightly frowning face",
    "\ud83d\ude44": " face with rolling eyes",
    "\ud83d\ude45": " person gesturing NO",
    "\ud83d\ude4f": " folded hands",
    "\ud83d\ude80": " rocket",
    "\ud83d\ude81": " helicopter",
    "\ud83d\ude82": " locomotive",
    "\ud83d\ude83": " railway car",
    "\ud83d\ude85": " bullet train",
    "\ud83d\ude86": " train",
    "\ud83d\ude87": " metro",
    "\ud83d\ude88": " light rail",
    "\ud83d\ude89": " station",
    "\ud83d\ude8a": " tram",
    "\ud83d\ude8b": " tram car",
    "\ud83d\ude8c": " bus",
    "\ud83d\ude8d": " oncoming bus",
    "\ud83d\ude8e": " trolleybus",
    "\ud83d\ude8f": " bus stop",
    "\ud83d\ude90": " minibus",
    "\ud83d\ude91": " ambulance",
    "\ud83d\ude93": " police car",
    "\ud83d\ude94": " oncoming police car",
    "\ud83d\ude95": " taxi",
    "\ud83d\ude96": " oncoming taxi",
    "\ud83d\ude97": " automobile",
    "\ud83d\ude98": " oncoming automobile",
    "\ud83d\ude99": " sport utility vehicle",
    "\ud83d\ude9a": " delivery truck",
    "\ud83d\ude9b": " articulated lorry",
    "\ud83d\udea1": " aerial tramway",
    "\ud83d\udea2": " ship",
    "\ud83d\udea3": " person rowing boat",
    "\ud83d\udea4": " speedboat",
    "\ud83d\udea5": " horizontal traffic light",
    "\ud83d\udea6": " vertical traffic light",
    "\ud83d\udea7": " construction",
    "\ud83d\udead": " no smoking",
    "\ud83d\udeae": " litter in bin sign",
    "\ud83d\udeb1": " non-potable water",
    "\ud83d\udeb2": " bicycle",
    "\ud83d\udeb3": " no bicycles",
    "\ud83d\udeb5": " person mountain biking",
    "\ud83d\udeb6": " person walking",
    "\ud83d\udeb7": " no pedestrians",
    "\ud83d\udeb8": " children crossing",
    "\ud83d\udeb9": " men\u2019s room",
    "\ud83d\udebe": " water closet",
    "\ud83d\udebf": " shower",
    "\ud83d\udec0": " person taking bath",
    "\ud83d\udec1": " bathtub",
    "\ud83d\udec5": " left luggage",
    "\ud83d\udecc": " person in bed",
    "\ud83d\uded0": " place of worship",
    "\ud83d\uded1": " stop sign",
    "\ud83d\uded2": " shopping cart",
    "\ud83d\uded5": " hindu temple",
    "\ud83d\uded6": " hut",
    "\ud83d\uded7": " elevator",
    "\ud83d\udedc": " wireless",
    "\ud83d\udedd": " playground slide",
    "\ud83d\udedf": " ring buoy",
    "\ud83d\udeeb": " airplane departure",
    "\ud83d\udeec": " airplane arrival",
    "\ud83d\udef4": " kick scooter",
    "\ud83d\udef6": " canoe",
    "\ud83d\udef7": " sled",
    "\ud83d\udef8": " flying saucer",
    "\ud83d\udef9": " skateboard",
    "\ud83d\udefa": " auto rickshaw",
    "\ud83d\udefb": " pickup truck",
    "\ud83d\udefc": " roller skate",
    "\ud83d\udfe0": " orange circle",
    "\ud83d\udfeb": " brown square",
    "\ud83d\udff0": " heavy equals sign",
    "\ud83e\udd0c": " pinched fingers",
    "\ud83e\udd0d": " white heart",
    "\ud83e\udd0f": " pinching hand",
    "\ud83e\udd10": " zipper-mouth face",
    "\ud83e\udd18": " sign of the horns",
    "\ud83e\udd19": " call me hand",
    "\ud83e\udd1e": " crossed fingers",
    "\ud83e\udd1f": " love-you gesture",
    "\ud83e\udd20": " cowboy hat face",
    "\ud83e\udd27": " sneezing face",
    "\ud83e\udd28": " face with raised eyebrow",
    "\ud83e\udd2f": " exploding head",
    "\ud83e\udd30": " pregnant woman",
    "\ud83e\udd31": " breast-feeding",
    "\ud83e\udd32": " palms up together",
    "\ud83e\udd33": " selfie",
    "\ud83e\udd3a": " person fencing",
    "\ud83e\udd3c": " people wrestling",
    "\ud83e\udd3e": " person playing handball",
    "\ud83e\udd3f": " diving mask",
    "\ud83e\udd40": " wilted flower",
    "\ud83e\udd45": " goal net",
    "\ud83e\udd47": " 1st place medal",
    "\ud83e\udd4b": " martial arts uniform",
    "\ud83e\udd4c": " curling stone",
    "\ud83e\udd4d": " lacrosse",
    "\ud83e\udd4f": " flying disc",
    "\ud83e\udd50": " croissant",
    "\ud83e\udd5e": " pancakes",
    "\ud83e\udd5f": " dumpling",
    "\ud83e\udd6b": " canned food",
    "\ud83e\udd6c": " leafy green",
    "\ud83e\udd70": " smiling face with hearts",
    "\ud83e\udd71": " yawning face",
    "\ud83e\udd72": " smiling face with tear",
    "\ud83e\udd73": " partying face",
    "\ud83e\udd76": " cold face",
    "\ud83e\udd77": " ninja",
    "\ud83e\udd78": " disguised face",
    "\ud83e\udd79": " face holding back tears",
    "\ud83e\udd7a": " pleading face",
    "\ud83e\udd7b": " sari",
    "\ud83e\udd7c": " lab coat",
    "\ud83e\udd7f": " flat shoe",
    "\ud83e\udd80": " crab",
    "\ud83e\udd84": " unicorn",
    "\ud83e\udd85": " eagle",
    "\ud83e\udd91": " squid",
    "\ud83e\udd92": " giraffe",
    "\ud83e\udd97": " cricket",
    "\ud83e\udd98": " kangaroo",
    "\ud83e\udda2": " swan",
    "\ud83e\udda3": " mammoth",
    "\ud83e\udda4": " dodo",
    "\ud83e\udda5": " sloth",
    "\ud83e\uddaa": " oyster",
    "\ud83e\uddab": " beaver",
    "\ud83e\uddad": " seal",
    "\ud83e\uddae": " guide dog",
    "\ud83e\uddaf": " white cane",
    "\ud83e\uddb0": " red hair",
    "\ud83e\uddb9": " supervillain",
    "\ud83e\uddba": " safety vest",
    "\ud83e\uddbf": " mechanical leg",
    "\ud83e\uddc0": " cheese wedge",
    "\ud83e\uddc1": " cupcake",
    "\ud83e\uddc2": " salt",
    "\ud83e\uddc3": " beverage box",
    "\ud83e\uddca": " ice",
    "\ud83e\uddcb": " bubble tea",
    "\ud83e\uddcc": " troll",
    "\ud83e\uddcd": " person standing",
    "\ud83e\uddcf": " deaf person",
    "\ud83e\uddd0": " face with monocle",
    "\ud83e\udde6": " socks",
    "\ud83e\udde7": " red envelope",
    "\ud83e\uddff": " nazar amulet",
    "\ud83e\ude70": " ballet shoes",
    "\ud83e\ude73": " shorts",
    "\ud83e\ude74": " thong sandal",
    "\ud83e\ude75": " light blue heart",
    "\ud83e\ude77": " pink heart",
    "\ud83e\ude78": " drop of blood",
    "\ud83e\ude7a": " stethoscope",
    "\ud83e\ude7b": " x-ray",
    "\ud83e\ude7c": " crutch",
    "\ud83e\ude80": " yo-yo",
    "\ud83e\ude82": " parachute",
    "\ud83e\ude83": " boomerang",
    "\ud83e\ude86": " nesting dolls",
    "\ud83e\ude87": " maracas",
    "\ud83e\ude88": " flute",
    "\ud83e\ude89": " harp",
    "\ud83e\ude8f": " shovel",
    "\ud83e\ude90": " ringed planet",
    "\ud83e\ude95": " banjo",
    "\ud83e\ude96": " military helmet",
    "\ud83e\udea8": " rock",
    "\ud83e\udea9": " mirror ball",
    "\ud83e\udeac": " hamsa",
    "\ud83e\udead": " folding hand fan",
    "\ud83e\udeaf": " khanda",
    "\ud83e\udeb0": " fly",
    "\ud83e\udeb6": " feather",
    "\ud83e\udeb7": " lotus",
    "\ud83e\udeba": " nest with eggs",
    "\ud83e\udebb": " hyacinth",
    "\ud83e\udebd": " wing",
    "\ud83e\udebe": " leafless tree",
    "\ud83e\udebf": " goose",
    "\ud83e\udec0": " anatomical heart",
    "\ud83e\udec2": " people hugging",
    "\ud83e\udec3": " pregnant man",
    "\ud83e\udec5": " person with crown",
    "\ud83e\udec6": " fingerprint",
    "\ud83e\udece": " moose",
    "\ud83e\udecf": " donkey",
    "\ud83e\uded0": " blueberries",
    "\ud83e\uded6": " teapot",
    "\ud83e\uded7": " pouring liquid",
    "\ud83e\uded9": " jar",
    "\ud83e\udeda": " ginger root",
    "\ud83e\udedb": " pea pod",
    "\ud83e\udedc": " root vegetable",
    "\ud83e\udedf": " splatter",
    "\ud83e\udee0": " melting face",
    "\ud83e\udee7": " bubbles",
    "\ud83e\udee8": " shaking face",
    "\ud83e\udee9": " face with bags under eyes",
    "\ud83e\udef0": " hand with index finger and thumb crossed",
    "\ud83e\udef6": " heart hands",
    "\ud83e\udef7": " leftwards pushing hand",
    "\ud83e\udef8": " rightwards pushing hand",
    "\u00a9\ufe0f": " copyright",
    "\u00ae\ufe0f": " registered",
    "\u203c\ufe0f": " double exclamation mark",
    "\u2049\ufe0f": " exclamation question mark",
    "\u2122\ufe0f": " trade mark",
    "\u2139\ufe0f": " information",
    "\u2194\ufe0f": " left-right arrow",
    "\u2195\ufe0f": " up-down arrow",
    "\u2196\ufe0f": " up-left arrow",
    "\u2197\ufe0f": " up-right arrow",
    "\u2198\ufe0f": " down-right arrow",
    "\u2199\ufe0f": " down-left arrow",
    "\u21a9\ufe0f": " right arrow curving left",
    "\u21aa\ufe0f": " left arrow curving right",
    "\u2328\ufe0f": " keyboard",
    "\u23cf\ufe0f": " eject button",
    "\u23ed\ufe0f": " next track button",
    "\u23ee\ufe0f": " last track button",
    "\u23ef\ufe0f": " play or pause button",
    "\u23f1\ufe0f": " stopwatch",
    "\u23f2\ufe0f": " timer clock",
    "\u23f8\ufe0f": " pause button",
    "\u23f9\ufe0f": " stop button",
    "\u23fa\ufe0f": " record button",
    "\u24c2\ufe0f": " circled M",
    "\u25aa\ufe0f": " black small square",
    "\u25ab\ufe0f": " white small square",
    "\u25b6\ufe0f": " play button",
    "\u25c0\ufe0f": " reverse button",
    "\u25fb\ufe0f": " white medium square",
    "\u25fc\ufe0f": " black medium square",
    "\u2600\ufe0f": " sun",
    "\u2601\ufe0f": " cloud",
    "\u2602\ufe0f": " umbrella",
    "\u2603\ufe0f": " snowman",
    "\u2604\ufe0f": " comet",
    "\u260e\ufe0f": " telephone",
    "\u2611\ufe0f": " check box with check",
    "\u2618\ufe0f": " shamrock",
    "\u261d\ufe0f": " index pointing up",
    "\u2620\ufe0f": " skull and crossbones",
    "\u2622\ufe0f": " radioactive",
    "\u2623\ufe0f": " biohazard",
    "\u2626\ufe0f": " orthodox cross",
    "\u262a\ufe0f": " star and crescent",
    "\u262e\ufe0f": " peace symbol",
    "\u262f\ufe0f": " yin yang",
    "\u2638\ufe0f": " wheel of dharma",
    "\u2639\ufe0f": " frowning face",
    "\u263a\ufe0f": " smiling face",
    "\u2640\ufe0f": " female sign",
    "\u2642\ufe0f": " male sign",
    "\u265f\ufe0f": " chess pawn",
    "\u2660\ufe0f": " spade suit",
    "\u2663\ufe0f": " club suit",
    "\u2665\ufe0f": " heart suit",
    "\u2666\ufe0f": " diamond suit",
    "\u2668\ufe0f": " hot springs",
    "\u267b\ufe0f": " recycling symbol",
    "\u267e\ufe0f": " infinity",
    "\u2692\ufe0f": " hammer and pick",
    "\u2694\ufe0f": " crossed swords",
    "\u2695\ufe0f": " medical symbol",
    "\u2696\ufe0f": " balance scale",
    "\u2697\ufe0f": " alembic",
    "\u2699\ufe0f": " gear",
    "\u269b\ufe0f": " atom symbol",
    "\u269c\ufe0f": " fleur-de-lis",
    "\u26a0\ufe0f": " warning",
    "\u26a7\ufe0f": " transgender symbol",
    "\u26b0\ufe0f": " coffin",
    "\u26b1\ufe0f": " funeral urn",
    "\u26c8\ufe0f": " cloud with lightning and rain",
    "\u26cf\ufe0f": " pick",
    "\u26d1\ufe0f": " rescue worker\u2019s helmet",
    "\u26d3\ufe0f": " chains",
    "\u26e9\ufe0f": " shinto shrine",
    "\u26f0\ufe0f": " mountain",
    "\u26f1\ufe0f": " umbrella on ground",
    "\u26f4\ufe0f": " ferry",
    "\u26f7\ufe0f": " skier",
    "\u26f8\ufe0f": " ice skate",
    "\u26f9\ufe0f": " person bouncing ball",
    "\u2702\ufe0f": " scissors",
    "\u2708\ufe0f": " airplane",
    "\u2709\ufe0f": " envelope",
    "\u270c\ufe0f": " victory hand",
    "\u270d\ufe0f": " writing hand",
    "\u270f\ufe0f": " pencil",
    "\u2712\ufe0f": " black nib",
    "\u2714\ufe0f": " check mark",
    "\u2716\ufe0f": " multiply",
    "\u271d\ufe0f": " latin cross",
    "\u2721\ufe0f": " star of David",
    "\u2733\ufe0f": " eight-spoked asterisk",
    "\u2734\ufe0f": " eight-pointed star",
    "\u2744\ufe0f": " snowflake",
    "\u2747\ufe0f": " sparkle",
    "\u2763\ufe0f": " heart exclamation",
    "\u2764\ufe0f": " red heart",
    "\u27a1\ufe0f": " right arrow",
    "\u2934\ufe0f": " right arrow curving up",
    "\u2935\ufe0f": " right arrow curving down",
    "\u2b05\ufe0f": " left arrow",
    "\u2b06\ufe0f": " up arrow",
    "\u2b07\ufe0f": " down arrow",
    "\u3030\ufe0f": " wavy dash",
    "\u303d\ufe0f": " part alternation mark",
    "\u3297\ufe0f": " Japanese \u201ccongratulations\u201d button",
    "\u3299\ufe0f": " Japanese \u201csecret\u201d button",
    "\ud83c\udd70\ufe0f": " A button (blood type)",
    "\ud83c\udd71\ufe0f": " B button (blood type)",
    "\ud83c\udd7e\ufe0f": " O button (blood type)",
    "\ud83c\udd7f\ufe0f": " P button",
    "\ud83c\ude02\ufe0f": " Japanese \u201cservice charge\u201d button",
    "\ud83c\ude37\ufe0f": " Japanese \u201cmonthly amount\u201d button",
    "\ud83c\udf21\ufe0f": " thermometer",
    "\ud83c\udf24\ufe0f": " sun behind small cloud",
    "\ud83c\udf25\ufe0f": " sun behind large cloud",
    "\ud83c\udf26\ufe0f": " sun behind rain cloud",
    "\ud83c\udf27\ufe0f": " cloud with rain",
    "\ud83c\udf28\ufe0f": " cloud with snow",
    "\ud83c\udf29\ufe0f": " cloud with lightning",
    "\ud83c\udf2a\ufe0f": " tornado",
    "\ud83c\udf2b\ufe0f": " fog",
    "\ud83c\udf2c\ufe0f": " wind face",
    "\ud83c\udf36\ufe0f": " hot pepper",
    "\ud83c\udf7d\ufe0f": " fork and knife with plate",
    "\ud83c\udf96\ufe0f": " military medal",
    "\ud83c\udf97\ufe0f": " reminder ribbon",
    "\ud83c\udf99\ufe0f": " studio microphone",
    "\ud83c\udf9a\ufe0f": " level slider",
    "\ud83c\udf9b\ufe0f": " control knobs",
    "\ud83c\udf9e\ufe0f": " film frames",
    "\ud83c\udf9f\ufe0f": " admission tickets",
    "\ud83c\udfcb\ufe0f": " person lifting weights",
    "\ud83c\udfcc\ufe0f": " person golfing",
    "\ud83c\udfcd\ufe0f": " motorcycle",
    "\ud83c\udfce\ufe0f": " racing car",
    "\ud83c\udfd4\ufe0f": " snow-capped mountain",
    "\ud83c\udfd5\ufe0f": " camping",
    "\ud83c\udfd6\ufe0f": " beach with umbrella",
    "\ud83c\udfd7\ufe0f": " building construction",
    "\ud83c\udfd8\ufe0f": " houses",
    "\ud83c\udfd9\ufe0f": " cityscape",
    "\ud83c\udfda\ufe0f": " derelict house",
    "\ud83c\udfdb\ufe0f": " classical building",
    "\ud83c\udfdc\ufe0f": " desert",
    "\ud83c\udfdd\ufe0f": " desert island",
    "\ud83c\udfde\ufe0f": " national park",
    "\ud83c\udfdf\ufe0f": " stadium",
    "\ud83c\udff3\ufe0f": " white flag",
    "\ud83c\udff5\ufe0f": " rosette",
    "\ud83c\udff7\ufe0f": " label",
    "\ud83d\udc3f\ufe0f": " chipmunk",
    "\ud83d\udc41\ufe0f": " eye",
    "\ud83d\udcfd\ufe0f": " film projector",
    "\ud83d\udd49\ufe0f": " om",
    "\ud83d\udd4a\ufe0f": " dove",
    "\ud83d\udd6f\ufe0f": " candle",
    "\ud83d\udd70\ufe0f": " mantelpiece clock",
    "\ud83d\udd73\ufe0f": " hole",
    "\ud83d\udd74\ufe0f": " person in suit levitating",
    "\ud83d\udd75\ufe0f": " detective",
    "\ud83d\udd76\ufe0f": " sunglasses",
    "\ud83d\udd77\ufe0f": " spider",
    "\ud83d\udd78\ufe0f": " spider web",
    "\ud83d\udd79\ufe0f": " joystick",
    "\ud83d\udd87\ufe0f": " linked paperclips",
    "\ud83d\udd8a\ufe0f": " pen",
    "\ud83d\udd8b\ufe0f": " fountain pen",
    "\ud83d\udd8c\ufe0f": " paintbrush",
    "\ud83d\udd8d\ufe0f": " crayon",
    "\ud83d\udd90\ufe0f": " hand with fingers splayed",
    "\ud83d\udda5\ufe0f": " desktop computer",
    "\ud83d\udda8\ufe0f": " printer",
    "\ud83d\uddb1\ufe0f": " computer mouse",
    "\ud83d\uddb2\ufe0f": " trackball",
    "\ud83d\uddbc\ufe0f": " framed picture",
    "\ud83d\uddc2\ufe0f": " card index dividers",
    "\ud83d\uddc3\ufe0f": " card file box",
    "\ud83d\uddc4\ufe0f": " file cabinet",
    "\ud83d\uddd1\ufe0f": " wastebasket",
    "\ud83d\uddd2\ufe0f": " spiral notepad",
    "\ud83d\uddd3\ufe0f": " spiral calendar",
    "\ud83d\udddc\ufe0f": " clamp",
    "\ud83d\udddd\ufe0f": " old key",
    "\ud83d\uddde\ufe0f": " rolled-up newspaper",
    "\ud83d\udde1\ufe0f": " dagger",
    "\ud83d\udde3\ufe0f": " speaking head",
    "\ud83d\udde8\ufe0f": " left speech bubble",
    "\ud83d\uddef\ufe0f": " right anger bubble",
    "\ud83d\uddf3\ufe0f": " ballot box with ballot",
    "\ud83d\uddfa\ufe0f": " world map",
    "\ud83d\udecb\ufe0f": " couch and lamp",
    "\ud83d\udecd\ufe0f": " shopping bags",
    "\ud83d\udece\ufe0f": " bellhop bell",
    "\ud83d\udecf\ufe0f": " bed",
    "\ud83d\udee0\ufe0f": " hammer and wrench",
    "\ud83d\udee1\ufe0f": " shield",
    "\ud83d\udee2\ufe0f": " oil drum",
    "\ud83d\udee3\ufe0f": " motorway",
    "\ud83d\udee4\ufe0f": " railway track",
    "\ud83d\udee5\ufe0f": " motor boat",
    "\ud83d\udee9\ufe0f": " small airplane",
    "\ud83d\udef0\ufe0f": " satellite",
    "\ud83d\udef3\ufe0f": " passenger ship",
    "#\ufe0f\u20e3": " keycap: \\x{23}",
    "*\ufe0f\u20e3": " keycap: *",
    "0\ufe0f\u20e3": " keycap: 0",
    "1\ufe0f\u20e3": " keycap: 1",
    "2\ufe0f\u20e3": " keycap: 2",
    "3\ufe0f\u20e3": " keycap: 3",
    "4\ufe0f\u20e3": " keycap: 4",
    "5\ufe0f\u20e3": " keycap: 5",
    "6\ufe0f\u20e3": " keycap: 6",
    "7\ufe0f\u20e3": " keycap: 7",
    "8\ufe0f\u20e3": " keycap: 8",
    "9\ufe0f\u20e3": " keycap: 9",
    "\ud83c\udde6\ud83c\udde8": " flag: Ascension Island",
    "\ud83c\udde6\ud83c\udde9": " flag: Andorra",
    "\ud83c\udde6\ud83c\uddea": " flag: United Arab Emirates",
    "\ud83c\udde6\ud83c\uddeb": " flag: Afghanistan",
    "\ud83c\udde6\ud83c\uddec": " flag: Antigua & Barbuda",
    "\ud83c\udde6\ud83c\uddee": " flag: Anguilla",
    "\ud83c\udde6\ud83c\uddf1": " flag: Albania",
    "\ud83c\udde6\ud83c\uddf2": " flag: Armenia",
    "\ud83c\udde6\ud83c\uddf4": " flag: Angola",
    "\ud83c\udde6\ud83c\uddf6": " flag: Antarctica",
    "\ud83c\udde6\ud83c\uddf7": " flag: Argentina",
    "\ud83c\udde6\ud83c\uddf8": " flag: American Samoa",
    "\ud83c\udde6\ud83c\uddf9": " flag: Austria",
    "\ud83c\udde6\ud83c\uddfa": " flag: Australia",
    "\ud83c\udde6\ud83c\uddfc": " flag: Aruba",
    "\ud83c\udde6\ud83c\uddfd": " flag: \u00c5land Islands",
    "\ud83c\udde6\ud83c\uddff": " flag: Azerbaijan",
    "\ud83c\udde7\ud83c\udde6": " flag: Bosnia & Herzegovina",
    "\ud83c\udde7\ud83c\udde7": " flag: Barbados",
    "\ud83c\udde7\ud83c\udde9": " flag: Bangladesh",
    "\ud83c\udde7\ud83c\uddea": " flag: Belgium",
    "\ud83c\udde7\ud83c\uddeb": " flag: Burkina Faso",
    "\ud83c\udde7\ud83c\uddec": " flag: Bulgaria",
    "\ud83c\udde7\ud83c\udded": " flag: Bahrain",
    "\ud83c\udde7\ud83c\uddee": " flag: Burundi",
    "\ud83c\udde7\ud83c\uddef": " flag: Benin",
    "\ud83c\udde7\ud83c\uddf1": " flag: St. Barth\u00e9lemy",
    "\ud83c\udde7\ud83c\uddf2": " flag: Bermuda",
    "\ud83c\udde7\ud83c\uddf3": " flag: Brunei",
    "\ud83c\udde7\ud83c\uddf4": " flag: Bolivia",
    "\ud83c\udde7\ud83c\uddf6": " flag: Caribbean Netherlands",
    "\ud83c\udde7\ud83c\uddf7": " flag: Brazil",
    "\ud83c\udde7\ud83c\uddf8": " flag: Bahamas",
    "\ud83c\udde7\ud83c\uddf9": " flag: Bhutan",
    "\ud83c\udde7\ud83c\uddfb": " flag: Bouvet Island",
    "\ud83c\udde7\ud83c\uddfc": " flag: Botswana",
    "\ud83c\udde7\ud83c\uddfe": " flag: Belarus",
    "\ud83c\udde7\ud83c\uddff": " flag: Belize",
    "\ud83c\udde8\ud83c\udde6": " flag: Canada",
    "\ud83c\udde8\ud83c\udde8": " flag: Cocos (Keeling) Islands",
    "\ud83c\udde8\ud83c\udde9": " flag: Congo - Kinshasa",
    "\ud83c\udde8\ud83c\uddeb": " flag: Central African Republic",
    "\ud83c\udde8\ud83c\uddec": " flag: Congo - Brazzaville",
    "\ud83c\udde8\ud83c\udded": " flag: Switzerland",
    "\ud83c\udde8\ud83c\uddee": " flag: C\u00f4te d\u2019Ivoire",
    "\ud83c\udde8\ud83c\uddf0": " flag: Cook Islands",
    "\ud83c\udde8\ud83c\uddf1": " flag: Chile",
    "\ud83c\udde8\ud83c\uddf2": " flag: Cameroon",
    "\ud83c\udde8\ud83c\uddf3": " flag: China",
    "\ud83c\udde8\ud83c\uddf4": " flag: Colombia",
    "\ud83c\udde8\ud83c\uddf5": " flag: Clipperton Island",
    "\ud83c\udde8\ud83c\uddf6": " flag: Sark",
    "\ud83c\udde8\ud83c\uddf7": " flag: Costa Rica",
    "\ud83c\udde8\ud83c\uddfa": " flag: Cuba",
    "\ud83c\udde8\ud83c\uddfb": " flag: Cape Verde",
    "\ud83c\udde8\ud83c\uddfc": " flag: Cura\u00e7ao",
    "\ud83c\udde8\ud83c\uddfd": " flag: Christmas Island",
    "\ud83c\udde8\ud83c\uddfe": " flag: Cyprus",
    "\ud83c\udde8\ud83c\uddff": " flag: Czechia",
    "\ud83c\udde9\ud83c\uddea": " flag: Germany",
    "\ud83c\udde9\ud83c\uddec": " flag: Diego Garcia",
    "\ud83c\udde9\ud83c\uddef": " flag: Djibouti",
    "\ud83c\udde9\ud83c\uddf0": " flag: Denmark",
    "\ud83c\udde9\ud83c\uddf2": " flag: Dominica",
    "\ud83c\udde9\ud83c\uddf4": " flag: Dominican Republic",
    "\ud83c\udde9\ud83c\uddff": " flag: Algeria",
    "\ud83c\uddea\ud83c\udde6": " flag: Ceuta & Melilla",
    "\ud83c\uddea\ud83c\udde8": " flag: Ecuador",
    "\ud83c\uddea\ud83c\uddea": " flag: Estonia",
    "\ud83c\uddea\ud83c\uddec": " flag: Egypt",
    "\ud83c\uddea\ud83c\udded": " flag: Western Sahara",
    "\ud83c\uddea\ud83c\uddf7": " flag: Eritrea",
    "\ud83c\uddea\ud83c\uddf8": " flag: Spain",
    "\ud83c\uddea\ud83c\uddf9": " flag: Ethiopia",
    "\ud83c\uddea\ud83c\uddfa": " flag: European Union",
    "\ud83c\uddeb\ud83c\uddee": " flag: Finland",
    "\ud83c\uddeb\ud83c\uddef": " flag: Fiji",
    "\ud83c\uddeb\ud83c\uddf0": " flag: Falkland Islands",
    "\ud83c\uddeb\ud83c\uddf2": " flag: Micronesia",
    "\ud83c\uddeb\ud83c\uddf4": " flag: Faroe Islands",
    "\ud83c\uddeb\ud83c\uddf7": " flag: France",
    "\ud83c\uddec\ud83c\udde6": " flag: Gabon",
    "\ud83c\uddec\ud83c\udde7": " flag: United Kingdom",
    "\ud83c\uddec\ud83c\udde9": " flag: Grenada",
    "\ud83c\uddec\ud83c\uddea": " flag: Georgia",
    "\ud83c\uddec\ud83c\uddeb": " flag: French Guiana",
    "\ud83c\uddec\ud83c\uddec": " flag: Guernsey",
    "\ud83c\uddec\ud83c\udded": " flag: Ghana",
    "\ud83c\uddec\ud83c\uddee": " flag: Gibraltar",
    "\ud83c\uddec\ud83c\uddf1": " flag: Greenland",
    "\ud83c\uddec\ud83c\uddf2": " flag: Gambia",
    "\ud83c\uddec\ud83c\uddf3": " flag: Guinea",
    "\ud83c\uddec\ud83c\uddf5": " flag: Guadeloupe",
    "\ud83c\uddec\ud83c\uddf6": " flag: Equatorial Guinea",
    "\ud83c\uddec\ud83c\uddf7": " flag: Greece",
    "\ud83c\uddec\ud83c\uddf8": " flag: South Georgia & South Sandwich Islands",
    "\ud83c\uddec\ud83c\uddf9": " flag: Guatemala",
    "\ud83c\uddec\ud83c\uddfa": " flag: Guam",
    "\ud83c\uddec\ud83c\uddfc": " flag: Guinea-Bissau",
    "\ud83c\uddec\ud83c\uddfe": " flag: Guyana",
    "\ud83c\udded\ud83c\uddf0": " flag: Hong Kong SAR China",
    "\ud83c\udded\ud83c\uddf2": " flag: Heard & McDonald Islands",
    "\ud83c\udded\ud83c\uddf3": " flag: Honduras",
    "\ud83c\udded\ud83c\uddf7": " flag: Croatia",
    "\ud83c\udded\ud83c\uddf9": " flag: Haiti",
    "\ud83c\udded\ud83c\uddfa": " flag: Hungary",
    "\ud83c\uddee\ud83c\udde8": " flag: Canary Islands",
    "\ud83c\uddee\ud83c\udde9": " flag: Indonesia",
    "\ud83c\uddee\ud83c\uddea": " flag: Ireland",
    "\ud83c\uddee\ud83c\uddf1": " flag: Israel",
    "\ud83c\uddee\ud83c\uddf2": " flag: Isle of Man",
    "\ud83c\uddee\ud83c\uddf3": " flag: India",
    "\ud83c\uddee\ud83c\uddf4": " flag: British Indian Ocean Territory",
    "\ud83c\uddee\ud83c\uddf6": " flag: Iraq",
    "\ud83c\uddee\ud83c\uddf7": " flag: Iran",
    "\ud83c\uddee\ud83c\uddf8": " flag: Iceland",
    "\ud83c\uddee\ud83c\uddf9": " flag: Italy",
    "\ud83c\uddef\ud83c\uddea": " flag: Jersey",
    "\ud83c\uddef\ud83c\uddf2": " flag: Jamaica",
    "\ud83c\uddef\ud83c\uddf4": " flag: Jordan",
    "\ud83c\uddef\ud83c\uddf5": " flag: Japan",
    "\ud83c\uddf0\ud83c\uddea": " flag: Kenya",
    "\ud83c\uddf0\ud83c\uddec": " flag: Kyrgyzstan",
    "\ud83c\uddf0\ud83c\udded": " flag: Cambodia",
    "\ud83c\uddf0\ud83c\uddee": " flag: Kiribati",
    "\ud83c\uddf0\ud83c\uddf2": " flag: Comoros",
    "\ud83c\uddf0\ud83c\uddf3": " flag: St. Kitts & Nevis",
    "\ud83c\uddf0\ud83c\uddf5": " flag: North Korea",
    "\ud83c\uddf0\ud83c\uddf7": " flag: South Korea",
    "\ud83c\uddf0\ud83c\uddfc": " flag: Kuwait",
    "\ud83c\uddf0\ud83c\uddfe": " flag: Cayman Islands",
    "\ud83c\uddf0\ud83c\uddff": " flag: Kazakhstan",
    "\ud83c\uddf1\ud83c\udde6": " flag: Laos",
    "\ud83c\uddf1\ud83c\udde7": " flag: Lebanon",
    "\ud83c\uddf1\ud83c\udde8": " flag: St. Lucia",
    "\ud83c\uddf1\ud83c\uddee": " flag: Liechtenstein",
    "\ud83c\uddf1\ud83c\uddf0": " flag: Sri Lanka",
    "\ud83c\uddf1\ud83c\uddf7": " flag: Liberia",
    "\ud83c\uddf1\ud83c\uddf8": " flag: Lesotho",
    "\ud83c\uddf1\ud83c\uddf9": " flag: Lithuania",
    "\ud83c\uddf1\ud83c\uddfa": " flag: Luxembourg",
    "\ud83c\uddf1\ud83c\uddfb": " flag: Latvia",
    "\ud83c\uddf1\ud83c\uddfe": " flag: Libya",
    "\ud83c\uddf2\ud83c\udde6": " flag: Morocco",
    "\ud83c\uddf2\ud83c\udde8": " flag: Monaco",
    "\ud83c\uddf2\ud83c\udde9": " flag: Moldova",
    "\ud83c\uddf2\ud83c\uddea": " flag: Montenegro",
    "\ud83c\uddf2\ud83c\uddeb": " flag: St. Martin",
    "\ud83c\uddf2\ud83c\uddec": " flag: Madagascar",
    "\ud83c\uddf2\ud83c\udded": " flag: Marshall Islands",
    "\ud83c\uddf2\ud83c\uddf0": " flag: North Macedonia",
    "\ud83c\uddf2\ud83c\uddf1": " flag: Mali",
    "\ud83c\uddf2\ud83c\uddf2": " flag: Myanmar (Burma)",
    "\ud83c\uddf2\ud83c\uddf3": " flag: Mongolia",
    "\ud83c\uddf2\ud83c\uddf4": " flag: Macao SAR China",
    "\ud83c\uddf2\ud83c\uddf5": " flag: Northern Mariana Islands",
    "\ud83c\uddf2\ud83c\uddf6": " flag: Martinique",
    "\ud83c\uddf2\ud83c\uddf7": " flag: Mauritania",
    "\ud83c\uddf2\ud83c\uddf8": " flag: Montserrat",
    "\ud83c\uddf2\ud83c\uddf9": " flag: Malta",
    "\ud83c\uddf2\ud83c\uddfa": " flag: Mauritius",
    "\ud83c\uddf2\ud83c\uddfb": " flag: Maldives",
    "\ud83c\uddf2\ud83c\uddfc": " flag: Malawi",
    "\ud83c\uddf2\ud83c\uddfd": " flag: Mexico",
    "\ud83c\uddf2\ud83c\uddfe": " flag: Malaysia",
    "\ud83c\uddf2\ud83c\uddff": " flag: Mozambique",
    "\ud83c\uddf3\ud83c\udde6": " flag: Namibia",
    "\ud83c\uddf3\ud83c\udde8": " flag: New Caledonia",
    "\ud83c\uddf3\ud83c\uddea": " flag: Niger",
    "\ud83c\uddf3\ud83c\uddeb": " flag: Norfolk Island",
    "\ud83c\uddf3\ud83c\uddec": " flag: Nigeria",
    "\ud83c\uddf3\ud83c\uddee": " flag: Nicaragua",
    "\ud83c\uddf3\ud83c\uddf1": " flag: Netherlands",
    "\ud83c\uddf3\ud83c\uddf4": " flag: Norway",
    "\ud83c\uddf3\ud83c\uddf5": " flag: Nepal",
    "\ud83c\uddf3\ud83c\uddf7": " flag: Nauru",
    "\ud83c\uddf3\ud83c\uddfa": " flag: Niue",
    "\ud83c\uddf3\ud83c\uddff": " flag: New Zealand",
    "\ud83c\uddf4\ud83c\uddf2": " flag: Oman",
    "\ud83c\uddf5\ud83c\udde6": " flag: Panama",
    "\ud83c\uddf5\ud83c\uddea": " flag: Peru",
    "\ud83c\uddf5\ud83c\uddeb": " flag: French Polynesia",
    "\ud83c\uddf5\ud83c\uddec": " flag: Papua New Guinea",
    "\ud83c\uddf5\ud83c\udded": " flag: Philippines",
    "\ud83c\uddf5\ud83c\uddf0": " flag: Pakistan",
    "\ud83c\uddf5\ud83c\uddf1": " flag: Poland",
    "\ud83c\uddf5\ud83c\uddf2": " flag: St. Pierre & Miquelon",
    "\ud83c\uddf5\ud83c\uddf3": " flag: Pitcairn Islands",
    "\ud83c\uddf5\ud83c\uddf7": " flag: Puerto Rico",
    "\ud83c\uddf5\ud83c\uddf8": " flag: Palestinian Territories",
    "\ud83c\uddf5\ud83c\uddf9": " flag: Portugal",
    "\ud83c\uddf5\ud83c\uddfc": " flag: Palau",
    "\ud83c\uddf5\ud83c\uddfe": " flag: Paraguay",
    "\ud83c\uddf6\ud83c\udde6": " flag: Qatar",
    "\ud83c\uddf7\ud83c\uddea": " flag: R\u00e9union",
    "\ud83c\uddf7\ud83c\uddf4": " flag: Romania",
    "\ud83c\uddf7\ud83c\uddf8": " flag: Serbia",
    "\ud83c\uddf7\ud83c\uddfa": " flag: Russia",
    "\ud83c\uddf7\ud83c\uddfc": " flag: Rwanda",
    "\ud83c\uddf8\ud83c\udde6": " flag: Saudi Arabia",
    "\ud83c\uddf8\ud83c\udde7": " flag: Solomon Islands",
    "\ud83c\uddf8\ud83c\udde8": " flag: Seychelles",
    "\ud83c\uddf8\ud83c\udde9": " flag: Sudan",
    "\ud83c\uddf8\ud83c\uddea": " flag: Sweden",
    "\ud83c\uddf8\ud83c\uddec": " flag: Singapore",
    "\ud83c\uddf8\ud83c\udded": " flag: St. Helena",
    "\ud83c\uddf8\ud83c\uddee": " flag: Slovenia",
    "\ud83c\uddf8\ud83c\uddef": " flag: Svalbard & Jan Mayen",
    "\ud83c\uddf8\ud83c\uddf0": " flag: Slovakia",
    "\ud83c\uddf8\ud83c\uddf1": " flag: Sierra Leone",
    "\ud83c\uddf8\ud83c\uddf2": " flag: San Marino",
    "\ud83c\uddf8\ud83c\uddf3": " flag: Senegal",
    "\ud83c\uddf8\ud83c\uddf4": " flag: Somalia",
    "\ud83c\uddf8\ud83c\uddf7": " flag: Suriname",
    "\ud83c\uddf8\ud83c\uddf8": " flag: South Sudan",
    "\ud83c\uddf8\ud83c\uddf9": " flag: S\u00e3o Tom\u00e9 & Pr\u00edncipe",
    "\ud83c\uddf8\ud83c\uddfb": " flag: El Salvador",
    "\ud83c\uddf8\ud83c\uddfd": " flag: Sint Maarten",
    "\ud83c\uddf8\ud83c\uddfe": " flag: Syria",
    "\ud83c\uddf8\ud83c\uddff": " flag: Eswatini",
    "\ud83c\uddf9\ud83c\udde6": " flag: Tristan da Cunha",
    "\ud83c\uddf9\ud83c\udde8": " flag: Turks & Caicos Islands",
    "\ud83c\uddf9\ud83c\udde9": " flag: Chad",
    "\ud83c\uddf9\ud83c\uddeb": " flag: French Southern Territories",
    "\ud83c\uddf9\ud83c\uddec": " flag: Togo",
    "\ud83c\uddf9\ud83c\udded": " flag: Thailand",
    "\ud83c\uddf9\ud83c\uddef": " flag: Tajikistan",
    "\ud83c\uddf9\ud83c\uddf0": " flag: Tokelau",
    "\ud83c\uddf9\ud83c\uddf1": " flag: Timor-Leste",
    "\ud83c\uddf9\ud83c\uddf2": " flag: Turkmenistan",
    "\ud83c\uddf9\ud83c\uddf3": " flag: Tunisia",
    "\ud83c\uddf9\ud83c\uddf4": " flag: Tonga",
    "\ud83c\uddf9\ud83c\uddf7": " flag: T\u00fcrkiye",
    "\ud83c\uddf9\ud83c\uddf9": " flag: Trinidad & Tobago",
    "\ud83c\uddf9\ud83c\uddfb": " flag: Tuvalu",
    "\ud83c\uddf9\ud83c\uddfc": " flag: Taiwan",
    "\ud83c\uddf9\ud83c\uddff": " flag: Tanzania",
    "\ud83c\uddfa\ud83c\udde6": " flag: Ukraine",
    "\ud83c\uddfa\ud83c\uddec": " flag: Uganda",
    "\ud83c\uddfa\ud83c\uddf2": " flag: U.S. Outlying Islands",
    "\ud83c\uddfa\ud83c\uddf3": " flag: United Nations",
    "\ud83c\uddfa\ud83c\uddf8": " flag: United States",
    "\ud83c\uddfa\ud83c\uddfe": " flag: Uruguay",
    "\ud83c\uddfa\ud83c\uddff": " flag: Uzbekistan",
    "\ud83c\uddfb\ud83c\udde6": " flag: Vatican City",
    "\ud83c\uddfb\ud83c\udde8": " flag: St. Vincent & Grenadines",
    "\ud83c\uddfb\ud83c\uddea": " flag: Venezuela",
    "\ud83c\uddfb\ud83c\uddec": " flag: British Virgin Islands",
    "\ud83c\uddfb\ud83c\uddee": " flag: U.S. Virgin Islands",
    "\ud83c\uddfb\ud83c\uddf3": " flag: Vietnam",
    "\ud83c\uddfb\ud83c\uddfa": " flag: Vanuatu",
    "\ud83c\uddfc\ud83c\uddeb": " flag: Wallis & Futuna",
    "\ud83c\uddfc\ud83c\uddf8": " flag: Samoa",
    "\ud83c\uddfd\ud83c\uddf0": " flag: Kosovo",
    "\ud83c\uddfe\ud83c\uddea": " flag: Yemen",
    "\ud83c\uddfe\ud83c\uddf9": " flag: Mayotte",
    "\ud83c\uddff\ud83c\udde6": " flag: South Africa",
    "\ud83c\uddff\ud83c\uddf2": " flag: Zambia",
    "\ud83c\uddff\ud83c\uddfc": " flag: Zimbabwe",
    "\ud83c\udff4\udb40\udc67\udb40\udc62\udb40\udc65\udb40\udc6e\udb40\udc67\udb40\udc7f": " flag: England",
    "\ud83c\udff4\udb40\udc67\udb40\udc62\udb40\udc73\udb40\udc63\udb40\udc74\udb40\udc7f": " flag: Scotland",
    "\ud83c\udff4\udb40\udc67\udb40\udc62\udb40\udc77\udb40\udc6c\udb40\udc73\udb40\udc7f": " flag: Wales",
    "\u261d\ud83c\udffb": " index pointing up: light skin tone",
    "\u261d\ud83c\udffc": " index pointing up: medium-light skin tone",
    "\u261d\ud83c\udffd": " index pointing up: medium skin tone",
    "\u261d\ud83c\udffe": " index pointing up: medium-dark skin tone",
    "\u261d\ud83c\udfff": " index pointing up: dark skin tone",
    "\u26f9\ud83c\udffb": " person bouncing ball: light skin tone",
    "\u26f9\ud83c\udffc": " person bouncing ball: medium-light skin tone",
    "\u26f9\ud83c\udffd": " person bouncing ball: medium skin tone",
    "\u26f9\ud83c\udffe": " person bouncing ball: medium-dark skin tone",
    "\u26f9\ud83c\udfff": " person bouncing ball: dark skin tone",
    "\u270a\ud83c\udffb": " raised fist: light skin tone",
    "\u270a\ud83c\udffc": " raised fist: medium-light skin tone",
    "\u270a\ud83c\udffd": " raised fist: medium skin tone",
    "\u270a\ud83c\udffe": " raised fist: medium-dark skin tone",
    "\u270a\ud83c\udfff": " raised fist: dark skin tone",
    "\u270b\ud83c\udffb": " raised hand: light skin tone",
    "\u270b\ud83c\udffc": " raised hand: medium-light skin tone",
    "\u270b\ud83c\udffd": " raised hand: medium skin tone",
    "\u270b\ud83c\udffe": " raised hand: medium-dark skin tone",
    "\u270b\ud83c\udfff": " raised hand: dark skin tone",
    "\u270c\ud83c\udffb": " victory hand: light skin tone",
    "\u270c\ud83c\udffc": " victory hand: medium-light skin tone",
    "\u270c\ud83c\udffd": " victory hand: medium skin tone",
    "\u270c\ud83c\udffe": " victory hand: medium-dark skin tone",
    "\u270c\ud83c\udfff": " victory hand: dark skin tone",
    "\u270d\ud83c\udffb": " writing hand: light skin tone",
    "\u270d\ud83c\udffc": " writing hand: medium-light skin tone",
    "\u270d\ud83c\udffd": " writing hand: medium skin tone",
    "\u270d\ud83c\udffe": " writing hand: medium-dark skin tone",
    "\u270d\ud83c\udfff": " writing hand: dark skin tone",
    "\ud83c\udf85\ud83c\udffb": " Santa Claus: light skin tone",
    "\ud83c\udf85\ud83c\udffc": " Santa Claus: medium-light skin tone",
    "\ud83c\udf85\ud83c\udffd": " Santa Claus: medium skin tone",
    "\ud83c\udf85\ud83c\udffe": " Santa Claus: medium-dark skin tone",
    "\ud83c\udf85\ud83c\udfff": " Santa Claus: dark skin tone",
    "\ud83c\udfc2\ud83c\udffb": " snowboarder: light skin tone",
    "\ud83c\udfc2\ud83c\udffc": " snowboarder: medium-light skin tone",
    "\ud83c\udfc2\ud83c\udffd": " snowboarder: medium skin tone",
    "\ud83c\udfc2\ud83c\udffe": " snowboarder: medium-dark skin tone",
    "\ud83c\udfc2\ud83c\udfff": " snowboarder: dark skin tone",
    "\ud83c\udfc3\ud83c\udffb": " person running: light skin tone",
    "\ud83c\udfc3\ud83c\udffc": " person running: medium-light skin tone",
    "\ud83c\udfc3\ud83c\udffd": " person running: medium skin tone",
    "\ud83c\udfc3\ud83c\udffe": " person running: medium-dark skin tone",
    "\ud83c\udfc3\ud83c\udfff": " person running: dark skin tone",
    "\ud83c\udfc4\ud83c\udffb": " person surfing: light skin tone",
    "\ud83c\udfc4\ud83c\udffc": " person surfing: medium-light skin tone",
    "\ud83c\udfc4\ud83c\udffd": " person surfing: medium skin tone",
    "\ud83c\udfc4\ud83c\udffe": " person surfing: medium-dark skin tone",
    "\ud83c\udfc4\ud83c\udfff": " person surfing: dark skin tone",
    "\ud83c\udfc7\ud83c\udffb": " horse racing: light skin tone",
    "\ud83c\udfc7\ud83c\udffc": " horse racing: medium-light skin tone",
    "\ud83c\udfc7\ud83c\udffd": " horse racing: medium skin tone",
    "\ud83c\udfc7\ud83c\udffe": " horse racing: medium-dark skin tone",
    "\ud83c\udfc7\ud83c\udfff": " horse racing: dark skin tone",
    "\ud83c\udfca\ud83c\udffb": " person swimming: light skin tone",
    "\ud83c\udfca\ud83c\udffc": " person swimming: medium-light skin tone",
    "\ud83c\udfca\ud83c\udffd": " person swimming: medium skin tone",
    "\ud83c\udfca\ud83c\udffe": " person swimming: medium-dark skin tone",
    "\ud83c\udfca\ud83c\udfff": " person swimming: dark skin tone",
    "\ud83c\udfcb\ud83c\udffb": " person lifting weights: light skin tone",
    "\ud83c\udfcb\ud83c\udffc": " person lifting weights: medium-light skin tone",
    "\ud83c\udfcb\ud83c\udffd": " person lifting weights: medium skin tone",
    "\ud83c\udfcb\ud83c\udffe": " person lifting weights: medium-dark skin tone",
    "\ud83c\udfcb\ud83c\udfff": " person lifting weights: dark skin tone",
    "\ud83c\udfcc\ud83c\udffb": " person golfing: light skin tone",
    "\ud83c\udfcc\ud83c\udffc": " person golfing: medium-light skin tone",
    "\ud83c\udfcc\ud83c\udffd": " person golfing: medium skin tone",
    "\ud83c\udfcc\ud83c\udffe": " person golfing: medium-dark skin tone",
    "\ud83c\udfcc\ud83c\udfff": " person golfing: dark skin tone",
    "\ud83d\udc42\ud83c\udffb": " ear: light skin tone",
    "\ud83d\udc42\ud83c\udffc": " ear: medium-light skin tone",
    "\ud83d\udc42\ud83c\udffd": " ear: medium skin tone",
    "\ud83d\udc42\ud83c\udffe": " ear: medium-dark skin tone",
    "\ud83d\udc42\ud83c\udfff": " ear: dark skin tone",
    "\ud83d\udc43\ud83c\udffb": " nose: light skin tone",
    "\ud83d\udc43\ud83c\udffc": " nose: medium-light skin tone",
    "\ud83d\udc43\ud83c\udffd": " nose: medium skin tone",
    "\ud83d\udc43\ud83c\udffe": " nose: medium-dark skin tone",
    "\ud83d\udc43\ud83c\udfff": " nose: dark skin tone",
    "\ud83d\udc46\ud83c\udffb": " backhand index pointing up: light skin tone",
    "\ud83d\udc46\ud83c\udffc": " backhand index pointing up: medium-light skin tone",
    "\ud83d\udc46\ud83c\udffd": " backhand index pointing up: medium skin tone",
    "\ud83d\udc46\ud83c\udffe": " backhand index pointing up: medium-dark skin tone",
    "\ud83d\udc46\ud83c\udfff": " backhand index pointing up: dark skin tone",
    "\ud83d\udc47\ud83c\udffb": " backhand index pointing down: light skin tone",
    "\ud83d\udc47\ud83c\udffc": " backhand index pointing down: medium-light skin tone",
    "\ud83d\udc47\ud83c\udffd": " backhand index pointing down: medium skin tone",
    "\ud83d\udc47\ud83c\udffe": " backhand index pointing down: medium-dark skin tone",
    "\ud83d\udc47\ud83c\udfff": " backhand index pointing down: dark skin tone",
    "\ud83d\udc48\ud83c\udffb": " backhand index pointing left: light skin tone",
    "\ud83d\udc48\ud83c\udffc": " backhand index pointing left: medium-light skin tone",
    "\ud83d\udc48\ud83c\udffd": " backhand index pointing left: medium skin tone",
    "\ud83d\udc48\ud83c\udffe": " backhand index pointing left: medium-dark skin tone",
    "\ud83d\udc48\ud83c\udfff": " backhand index pointing left: dark skin tone",
    "\ud83d\udc49\ud83c\udffb": " backhand index pointing right: light skin tone",
    "\ud83d\udc49\ud83c\udffc": " backhand index pointing right: medium-light skin tone",
    "\ud83d\udc49\ud83c\udffd": " backhand index pointing right: medium skin tone",
    "\ud83d\udc49\ud83c\udffe": " backhand index pointing right: medium-dark skin tone",
    "\ud83d\udc49\ud83c\udfff": " backhand index pointing right: dark skin tone",
    "\ud83d\udc4a\ud83c\udffb": " oncoming fist: light skin tone",
    "\ud83d\udc4a\ud83c\udffc": " oncoming fist: medium-light skin tone",
    "\ud83d\udc4a\ud83c\udffd": " oncoming fist: medium skin tone",
    "\ud83d\udc4a\ud83c\udffe": " oncoming fist: medium-dark skin tone",
    "\ud83d\udc4a\ud83c\udfff": " oncoming fist: dark skin tone",
    "\ud83d\udc4b\ud83c\udffb": " waving hand: light skin tone",
    "\ud83d\udc4b\ud83c\udffc": " waving hand: medium-light skin tone",
    "\ud83d\udc4b\ud83c\udffd": " waving hand: medium skin tone",
    "\ud83d\udc4b\ud83c\udffe": " waving hand: medium-dark skin tone",
    "\ud83d\udc4b\ud83c\udfff": " waving hand: dark skin tone",
    "\ud83d\udc4c\ud83c\udffb": " OK hand: light skin tone",
    "\ud83d\udc4c\ud83c\udffc": " OK hand: medium-light skin tone",
    "\ud83d\udc4c\ud83c\udffd": " OK hand: medium skin tone",
    "\ud83d\udc4c\ud83c\udffe": " OK hand: medium-dark skin tone",
    "\ud83d\udc4c\ud83c\udfff": " OK hand: dark skin tone",
    "\ud83d\udc4d\ud83c\udffb": " thumbs up: light skin tone",
    "\ud83d\udc4d\ud83c\udffc": " thumbs up: medium-light skin tone",
    "\ud83d\udc4d\ud83c\udffd": " thumbs up: medium skin tone",
    "\ud83d\udc4d\ud83c\udffe": " thumbs up: medium-dark skin tone",
    "\ud83d\udc4d\ud83c\udfff": " thumbs up: dark skin tone",
    "\ud83d\udc4e\ud83c\udffb": " thumbs down: light skin tone",
    "\ud83d\udc4e\ud83c\udffc": " thumbs down: medium-light skin tone",
    "\ud83d\udc4e\ud83c\udffd": " thumbs down: medium skin tone",
    "\ud83d\udc4e\ud83c\udffe": " thumbs down: medium-dark skin tone",
    "\ud83d\udc4e\ud83c\udfff": " thumbs down: dark skin tone",
    "\ud83d\udc4f\ud83c\udffb": " clapping hands: light skin tone",
    "\ud83d\udc4f\ud83c\udffc": " clapping hands: medium-light skin tone",
    "\ud83d\udc4f\ud83c\udffd": " clapping hands: medium skin tone",
    "\ud83d\udc4f\ud83c\udffe": " clapping hands: medium-dark skin tone",
    "\ud83d\udc4f\ud83c\udfff": " clapping hands: dark skin tone",
    "\ud83d\udc50\ud83c\udffb": " open hands: light skin tone",
    "\ud83d\udc50\ud83c\udffc": " open hands: medium-light skin tone",
    "\ud83d\udc50\ud83c\udffd": " open hands: medium skin tone",
    "\ud83d\udc50\ud83c\udffe": " open hands: medium-dark skin tone",
    "\ud83d\udc50\ud83c\udfff": " open hands: dark skin tone",
    "\ud83d\udc66\ud83c\udffb": " boy: light skin tone",
    "\ud83d\udc66\ud83c\udffc": " boy: medium-light skin tone",
    "\ud83d\udc66\ud83c\udffd": " boy: medium skin tone",
    "\ud83d\udc66\ud83c\udffe": " boy: medium-dark skin tone",
    "\ud83d\udc66\ud83c\udfff": " boy: dark skin tone",
    "\ud83d\udc67\ud83c\udffb": " girl: light skin tone",
    "\ud83d\udc67\ud83c\udffc": " girl: medium-light skin tone",
    "\ud83d\udc67\ud83c\udffd": " girl: medium skin tone",
    "\ud83d\udc67\ud83c\udffe": " girl: medium-dark skin tone",
    "\ud83d\udc67\ud83c\udfff": " girl: dark skin tone",
    "\ud83d\udc68\ud83c\udffb": " man: light skin tone",
    "\ud83d\udc68\ud83c\udffc": " man: medium-light skin tone",
    "\ud83d\udc68\ud83c\udffd": " man: medium skin tone",
    "\ud83d\udc68\ud83c\udffe": " man: medium-dark skin tone",
    "\ud83d\udc68\ud83c\udfff": " man: dark skin tone",
    "\ud83d\udc69\ud83c\udffb": " woman: light skin tone",
    "\ud83d\udc69\ud83c\udffc": " woman: medium-light skin tone",
    "\ud83d\udc69\ud83c\udffd": " woman: medium skin tone",
    "\ud83d\udc69\ud83c\udffe": " woman: medium-dark skin tone",
    "\ud83d\udc69\ud83c\udfff": " woman: dark skin tone",
    "\ud83d\udc6b\ud83c\udffb": " woman and man holding hands: light skin tone",
    "\ud83d\udc6b\ud83c\udffc": " woman and man holding hands: medium-light skin tone",
    "\ud83d\udc6b\ud83c\udffd": " woman and man holding hands: medium skin tone",
    "\ud83d\udc6b\ud83c\udffe": " woman and man holding hands: medium-dark skin tone",
    "\ud83d\udc6b\ud83c\udfff": " woman and man holding hands: dark skin tone",
    "\ud83d\udc6c\ud83c\udffb": " men holding hands: light skin tone",
    "\ud83d\udc6c\ud83c\udffc": " men holding hands: medium-light skin tone",
    "\ud83d\udc6c\ud83c\udffd": " men holding hands: medium skin tone",
    "\ud83d\udc6c\ud83c\udffe": " men holding hands: medium-dark skin tone",
    "\ud83d\udc6c\ud83c\udfff": " men holding hands: dark skin tone",
    "\ud83d\udc6d\ud83c\udffb": " women holding hands: light skin tone",
    "\ud83d\udc6d\ud83c\udffc": " women holding hands: medium-light skin tone",
    "\ud83d\udc6d\ud83c\udffd": " women holding hands: medium skin tone",
    "\ud83d\udc6d\ud83c\udffe": " women holding hands: medium-dark skin tone",
    "\ud83d\udc6d\ud83c\udfff": " women holding hands: dark skin tone",
    "\ud83d\udc6e\ud83c\udffb": " police officer: light skin tone",
    "\ud83d\udc6e\ud83c\udffc": " police officer: medium-light skin tone",
    "\ud83d\udc6e\ud83c\udffd": " police officer: medium skin tone",
    "\ud83d\udc6e\ud83c\udffe": " police officer: medium-dark skin tone",
    "\ud83d\udc6e\ud83c\udfff": " police officer: dark skin tone",
    "\ud83d\udc70\ud83c\udffb": " person with veil: light skin tone",
    "\ud83d\udc70\ud83c\udffc": " person with veil: medium-light skin tone",
    "\ud83d\udc70\ud83c\udffd": " person with veil: medium skin tone",
    "\ud83d\udc70\ud83c\udffe": " person with veil: medium-dark skin tone",
    "\ud83d\udc70\ud83c\udfff": " person with veil: dark skin tone",
    "\ud83d\udc71\ud83c\udffb": " person: light skin tone, blond hair",
    "\ud83d\udc71\ud83c\udffc": " person: medium-light skin tone, blond hair",
    "\ud83d\udc71\ud83c\udffd": " person: medium skin tone, blond hair",
    "\ud83d\udc71\ud83c\udffe": " person: medium-dark skin tone, blond hair",
    "\ud83d\udc71\ud83c\udfff": " person: dark skin tone, blond hair",
    "\ud83d\udc72\ud83c\udffb": " person with skullcap: light skin tone",
    "\ud83d\udc72\ud83c\udffc": " person with skullcap: medium-light skin tone",
    "\ud83d\udc72\ud83c\udffd": " person with skullcap: medium skin tone",
    "\ud83d\udc72\ud83c\udffe": " person with skullcap: medium-dark skin tone",
    "\ud83d\udc72\ud83c\udfff": " person with skullcap: dark skin tone",
    "\ud83d\udc73\ud83c\udffb": " person wearing turban: light skin tone",
    "\ud83d\udc73\ud83c\udffc": " person wearing turban: medium-light skin tone",
    "\ud83d\udc73\ud83c\udffd": " person wearing turban: medium skin tone",
    "\ud83d\udc73\ud83c\udffe": " person wearing turban: medium-dark skin tone",
    "\ud83d\udc73\ud83c\udfff": " person wearing turban: dark skin tone",
    "\ud83d\udc74\ud83c\udffb": " old man: light skin tone",
    "\ud83d\udc74\ud83c\udffc": " old man: medium-light skin tone",
    "\ud83d\udc74\ud83c\udffd": " old man: medium skin tone",
    "\ud83d\udc74\ud83c\udffe": " old man: medium-dark skin tone",
    "\ud83d\udc74\ud83c\udfff": " old man: dark skin tone",
    "\ud83d\udc75\ud83c\udffb": " old woman: light skin tone",
    "\ud83d\udc75\ud83c\udffc": " old woman: medium-light skin tone",
    "\ud83d\udc75\ud83c\udffd": " old woman: medium skin tone",
    "\ud83d\udc75\ud83c\udffe": " old woman: medium-dark skin tone",
    "\ud83d\udc75\ud83c\udfff": " old woman: dark skin tone",
    "\ud83d\udc76\ud83c\udffb": " baby: light skin tone",
    "\ud83d\udc76\ud83c\udffc": " baby: medium-light skin tone",
    "\ud83d\udc76\ud83c\udffd": " baby: medium skin tone",
    "\ud83d\udc76\ud83c\udffe": " baby: medium-dark skin tone",
    "\ud83d\udc76\ud83c\udfff": " baby: dark skin tone",
    "\ud83d\udc77\ud83c\udffb": " construction worker: light skin tone",
    "\ud83d\udc77\ud83c\udffc": " construction worker: medium-light skin tone",
    "\ud83d\udc77\ud83c\udffd": " construction worker: medium skin tone",
    "\ud83d\udc77\ud83c\udffe": " construction worker: medium-dark skin tone",
    "\ud83d\udc77\ud83c\udfff": " construction worker: dark skin tone",
    "\ud83d\udc78\ud83c\udffb": " princess: light skin tone",
    "\ud83d\udc78\ud83c\udffc": " princess: medium-light skin tone",
    "\ud83d\udc78\ud83c\udffd": " princess: medium skin tone",
    "\ud83d\udc78\ud83c\udffe": " princess: medium-dark skin tone",
    "\ud83d\udc78\ud83c\udfff": " princess: dark skin tone",
    "\ud83d\udc7c\ud83c\udffb": " baby angel: light skin tone",
    "\ud83d\udc7c\ud83c\udffc": " baby angel: medium-light skin tone",
    "\ud83d\udc7c\ud83c\udffd": " baby angel: medium skin tone",
    "\ud83d\udc7c\ud83c\udffe": " baby angel: medium-dark skin tone",
    "\ud83d\udc7c\ud83c\udfff": " baby angel: dark skin tone",
    "\ud83d\udc81\ud83c\udffb": " person tipping hand: light skin tone",
    "\ud83d\udc81\ud83c\udffc": " person tipping hand: medium-light skin tone",
    "\ud83d\udc81\ud83c\udffd": " person tipping hand: medium skin tone",
    "\ud83d\udc81\ud83c\udffe": " person tipping hand: medium-dark skin tone",
    "\ud83d\udc81\ud83c\udfff": " person tipping hand: dark skin tone",
    "\ud83d\udc82\ud83c\udffb": " guard: light skin tone",
    "\ud83d\udc82\ud83c\udffc": " guard: medium-light skin tone",
    "\ud83d\udc82\ud83c\udffd": " guard: medium skin tone",
    "\ud83d\udc82\ud83c\udffe": " guard: medium-dark skin tone",
    "\ud83d\udc82\ud83c\udfff": " guard: dark skin tone",
    "\ud83d\udc83\ud83c\udffb": " woman dancing: light skin tone",
    "\ud83d\udc83\ud83c\udffc": " woman dancing: medium-light skin tone",
    "\ud83d\udc83\ud83c\udffd": " woman dancing: medium skin tone",
    "\ud83d\udc83\ud83c\udffe": " woman dancing: medium-dark skin tone",
    "\ud83d\udc83\ud83c\udfff": " woman dancing: dark skin tone",
    "\ud83d\udc85\ud83c\udffb": " nail polish: light skin tone",
    "\ud83d\udc85\ud83c\udffc": " nail polish: medium-light skin tone",
    "\ud83d\udc85\ud83c\udffd": " nail polish: medium skin tone",
    "\ud83d\udc85\ud83c\udffe": " nail polish: medium-dark skin tone",
    "\ud83d\udc85\ud83c\udfff": " nail polish: dark skin tone",
    "\ud83d\udc86\ud83c\udffb": " person getting massage: light skin tone",
    "\ud83d\udc86\ud83c\udffc": " person getting massage: medium-light skin tone",
    "\ud83d\udc86\ud83c\udffd": " person getting massage: medium skin tone",
    "\ud83d\udc86\ud83c\udffe": " person getting massage: medium-dark skin tone",
    "\ud83d\udc86\ud83c\udfff": " person getting massage: dark skin tone",
    "\ud83d\udc87\ud83c\udffb": " person getting haircut: light skin tone",
    "\ud83d\udc87\ud83c\udffc": " person getting haircut: medium-light skin tone",
    "\ud83d\udc87\ud83c\udffd": " person getting haircut: medium skin tone",
    "\ud83d\udc87\ud83c\udffe": " person getting haircut: medium-dark skin tone",
    "\ud83d\udc87\ud83c\udfff": " person getting haircut: dark skin tone",
    "\ud83d\udc8f\ud83c\udffb": " kiss: light skin tone",
    "\ud83d\udc8f\ud83c\udffc": " kiss: medium-light skin tone",
    "\ud83d\udc8f\ud83c\udffd": " kiss: medium skin tone",
    "\ud83d\udc8f\ud83c\udffe": " kiss: medium-dark skin tone",
    "\ud83d\udc8f\ud83c\udfff": " kiss: dark skin tone",
    "\ud83d\udc91\ud83c\udffb": " couple with heart: light skin tone",
    "\ud83d\udc91\ud83c\udffc": " couple with heart: medium-light skin tone",
    "\ud83d\udc91\ud83c\udffd": " couple with heart: medium skin tone",
    "\ud83d\udc91\ud83c\udffe": " couple with heart: medium-dark skin tone",
    "\ud83d\udc91\ud83c\udfff": " couple with heart: dark skin tone",
    "\ud83d\udcaa\ud83c\udffb": " flexed biceps: light skin tone",
    "\ud83d\udcaa\ud83c\udffc": " flexed biceps: medium-light skin tone",
    "\ud83d\udcaa\ud83c\udffd": " flexed biceps: medium skin tone",
    "\ud83d\udcaa\ud83c\udffe": " flexed biceps: medium-dark skin tone",
    "\ud83d\udcaa\ud83c\udfff": " flexed biceps: dark skin tone",
    "\ud83d\udd74\ud83c\udffb": " person in suit levitating: light skin tone",
    "\ud83d\udd74\ud83c\udffc": " person in suit levitating: medium-light skin tone",
    "\ud83d\udd74\ud83c\udffd": " person in suit levitating: medium skin tone",
    "\ud83d\udd74\ud83c\udffe": " person in suit levitating: medium-dark skin tone",
    "\ud83d\udd74\ud83c\udfff": " person in suit levitating: dark skin tone",
    "\ud83d\udd75\ud83c\udffb": " detective: light skin tone",
    "\ud83d\udd75\ud83c\udffc": " detective: medium-light skin tone",
    "\ud83d\udd75\ud83c\udffd": " detective: medium skin tone",
    "\ud83d\udd75\ud83c\udffe": " detective: medium-dark skin tone",
    "\ud83d\udd75\ud83c\udfff": " detective: dark skin tone",
    "\ud83d\udd7a\ud83c\udffb": " man dancing: light skin tone",
    "\ud83d\udd7a\ud83c\udffc": " man dancing: medium-light skin tone",
    "\ud83d\udd7a\ud83c\udffd": " man dancing: medium skin tone",
    "\ud83d\udd7a\ud83c\udffe": " man dancing: medium-dark skin tone",
    "\ud83d\udd7a\ud83c\udfff": " man dancing: dark skin tone",
    "\ud83d\udd90\ud83c\udffb": " hand with fingers splayed: light skin tone",
    "\ud83d\udd90\ud83c\udffc": " hand with fingers splayed: medium-light skin tone",
    "\ud83d\udd90\ud83c\udffd": " hand with fingers splayed: medium skin tone",
    "\ud83d\udd90\ud83c\udffe": " hand with fingers splayed: medium-dark skin tone",
    "\ud83d\udd90\ud83c\udfff": " hand with fingers splayed: dark skin tone",
    "\ud83d\udd95\ud83c\udffb": " middle finger: light skin tone",
    "\ud83d\udd95\ud83c\udffc": " middle finger: medium-light skin tone",
    "\ud83d\udd95\ud83c\udffd": " middle finger: medium skin tone",
    "\ud83d\udd95\ud83c\udffe": " middle finger: medium-dark skin tone",
    "\ud83d\udd95\ud83c\udfff": " middle finger: dark skin tone",
    "\ud83d\udd96\ud83c\udffb": " vulcan salute: light skin tone",
    "\ud83d\udd96\ud83c\udffc": " vulcan salute: medium-light skin tone",
    "\ud83d\udd96\ud83c\udffd": " vulcan salute: medium skin tone",
    "\ud83d\udd96\ud83c\udffe": " vulcan salute: medium-dark skin tone",
    "\ud83d\udd96\ud83c\udfff": " vulcan salute: dark skin tone",
    "\ud83d\ude45\ud83c\udffb": " person gesturing NO: light skin tone",
    "\ud83d\ude45\ud83c\udffc": " person gesturing NO: medium-light skin tone",
    "\ud83d\ude45\ud83c\udffd": " person gesturing NO: medium skin tone",
    "\ud83d\ude45\ud83c\udffe": " person gesturing NO: medium-dark skin tone",
    "\ud83d\ude45\ud83c\udfff": " person gesturing NO: dark skin tone",
    "\ud83d\ude46\ud83c\udffb": " person gesturing OK: light skin tone",
    "\ud83d\ude46\ud83c\udffc": " person gesturing OK: medium-light skin tone",
    "\ud83d\ude46\ud83c\udffd": " person gesturing OK: medium skin tone",
    "\ud83d\ude46\ud83c\udffe": " person gesturing OK: medium-dark skin tone",
    "\ud83d\ude46\ud83c\udfff": " person gesturing OK: dark skin tone",
    "\ud83d\ude47\ud83c\udffb": " person bowing: light skin tone",
    "\ud83d\ude47\ud83c\udffc": " person bowing: medium-light skin tone",
    "\ud83d\ude47\ud83c\udffd": " person bowing: medium skin tone",
    "\ud83d\ude47\ud83c\udffe": " person bowing: medium-dark skin tone",
    "\ud83d\ude47\ud83c\udfff": " person bowing: dark skin tone",
    "\ud83d\ude4b\ud83c\udffb": " person raising hand: light skin tone",
    "\ud83d\ude4b\ud83c\udffc": " person raising hand: medium-light skin tone",
    "\ud83d\ude4b\ud83c\udffd": " person raising hand: medium skin tone",
    "\ud83d\ude4b\ud83c\udffe": " person raising hand: medium-dark skin tone",
    "\ud83d\ude4b\ud83c\udfff": " person raising hand: dark skin tone",
    "\ud83d\ude4c\ud83c\udffb": " raising hands: light skin tone",
    "\ud83d\ude4c\ud83c\udffc": " raising hands: medium-light skin tone",
    "\ud83d\ude4c\ud83c\udffd": " raising hands: medium skin tone",
    "\ud83d\ude4c\ud83c\udffe": " raising hands: medium-dark skin tone",
    "\ud83d\ude4c\ud83c\udfff": " raising hands: dark skin tone",
    "\ud83d\ude4d\ud83c\udffb": " person frowning: light skin tone",
    "\ud83d\ude4d\ud83c\udffc": " person frowning: medium-light skin tone",
    "\ud83d\ude4d\ud83c\udffd": " person frowning: medium skin tone",
    "\ud83d\ude4d\ud83c\udffe": " person frowning: medium-dark skin tone",
    "\ud83d\ude4d\ud83c\udfff": " person frowning: dark skin tone",
    "\ud83d\ude4e\ud83c\udffb": " person pouting: light skin tone",
    "\ud83d\ude4e\ud83c\udffc": " person pouting: medium-light skin tone",
    "\ud83d\ude4e\ud83c\udffd": " person pouting: medium skin tone",
    "\ud83d\ude4e\ud83c\udffe": " person pouting: medium-dark skin tone",
    "\ud83d\ude4e\ud83c\udfff": " person pouting: dark skin tone",
    "\ud83d\ude4f\ud83c\udffb": " folded hands: light skin tone",
    "\ud83d\ude4f\ud83c\udffc": " folded hands: medium-light skin tone",
    "\ud83d\ude4f\ud83c\udffd": " folded hands: medium skin tone",
    "\ud83d\ude4f\ud83c\udffe": " folded hands: medium-dark skin tone",
    "\ud83d\ude4f\ud83c\udfff": " folded hands: dark skin tone",
    "\ud83d\udea3\ud83c\udffb": " person rowing boat: light skin tone",
    "\ud83d\udea3\ud83c\udffc": " person rowing boat: medium-light skin tone",
    "\ud83d\udea3\ud83c\udffd": " person rowing boat: medium skin tone",
    "\ud83d\udea3\ud83c\udffe": " person rowing boat: medium-dark skin tone",
    "\ud83d\udea3\ud83c\udfff": " person rowing boat: dark skin tone",
    "\ud83d\udeb4\ud83c\udffb": " person biking: light skin tone",
    "\ud83d\udeb4\ud83c\udffc": " person biking: medium-light skin tone",
    "\ud83d\udeb4\ud83c\udffd": " person biking: medium skin tone",
    "\ud83d\udeb4\ud83c\udffe": " person biking: medium-dark skin tone",
    "\ud83d\udeb4\ud83c\udfff": " person biking: dark skin tone",
    "\ud83d\udeb5\ud83c\udffb": " person mountain biking: light skin tone",
    "\ud83d\udeb5\ud83c\udffc": " person mountain biking: medium-light skin tone",
    "\ud83d\udeb5\ud83c\udffd": " person mountain biking: medium skin tone",
    "\ud83d\udeb5\ud83c\udffe": " person mountain biking: medium-dark skin tone",
    "\ud83d\udeb5\ud83c\udfff": " person mountain biking: dark skin tone",
    "\ud83d\udeb6\ud83c\udffb": " person walking: light skin tone",
    "\ud83d\udeb6\ud83c\udffc": " person walking: medium-light skin tone",
    "\ud83d\udeb6\ud83c\udffd": " person walking: medium skin tone",
    "\ud83d\udeb6\ud83c\udffe": " person walking: medium-dark skin tone",
    "\ud83d\udeb6\ud83c\udfff": " person walking: dark skin tone",
    "\ud83d\udec0\ud83c\udffb": " person taking bath: light skin tone",
    "\ud83d\udec0\ud83c\udffc": " person taking bath: medium-light skin tone",
    "\ud83d\udec0\ud83c\udffd": " person taking bath: medium skin tone",
    "\ud83d\udec0\ud83c\udffe": " person taking bath: medium-dark skin tone",
    "\ud83d\udec0\ud83c\udfff": " person taking bath: dark skin tone",
    "\ud83d\udecc\ud83c\udffb": " person in bed: light skin tone",
    "\ud83d\udecc\ud83c\udffc": " person in bed: medium-light skin tone",
    "\ud83d\udecc\ud83c\udffd": " person in bed: medium skin tone",
    "\ud83d\udecc\ud83c\udffe": " person in bed: medium-dark skin tone",
    "\ud83d\udecc\ud83c\udfff": " person in bed: dark skin tone",
    "\ud83e\udd0c\ud83c\udffb": " pinched fingers: light skin tone",
    "\ud83e\udd0c\ud83c\udffc": " pinched fingers: medium-light skin tone",
    "\ud83e\udd0c\ud83c\udffd": " pinched fingers: medium skin tone",
    "\ud83e\udd0c\ud83c\udffe": " pinched fingers: medium-dark skin tone",
    "\ud83e\udd0c\ud83c\udfff": " pinched fingers: dark skin tone",
    "\ud83e\udd0f\ud83c\udffb": " pinching hand: light skin tone",
    "\ud83e\udd0f\ud83c\udffc": " pinching hand: medium-light skin tone",
    "\ud83e\udd0f\ud83c\udffd": " pinching hand: medium skin tone",
    "\ud83e\udd0f\ud83c\udffe": " pinching hand: medium-dark skin tone",
    "\ud83e\udd0f\ud83c\udfff": " pinching hand: dark skin tone",
    "\ud83e\udd18\ud83c\udffb": " sign of the horns: light skin tone",
    "\ud83e\udd18\ud83c\udffc": " sign of the horns: medium-light skin tone",
    "\ud83e\udd18\ud83c\udffd": " sign of the horns: medium skin tone",
    "\ud83e\udd18\ud83c\udffe": " sign of the horns: medium-dark skin tone",
    "\ud83e\udd18\ud83c\udfff": " sign of the horns: dark skin tone",
    "\ud83e\udd19\ud83c\udffb": " call me hand: light skin tone",
    "\ud83e\udd19\ud83c\udffc": " call me hand: medium-light skin tone",
    "\ud83e\udd19\ud83c\udffd": " call me hand: medium skin tone",
    "\ud83e\udd19\ud83c\udffe": " call me hand: medium-dark skin tone",
    "\ud83e\udd19\ud83c\udfff": " call me hand: dark skin tone",
    "\ud83e\udd1a\ud83c\udffb": " raised back of hand: light skin tone",
    "\ud83e\udd1a\ud83c\udffc": " raised back of hand: medium-light skin tone",
    "\ud83e\udd1a\ud83c\udffd": " raised back of hand: medium skin tone",
    "\ud83e\udd1a\ud83c\udffe": " raised back of hand: medium-dark skin tone",
    "\ud83e\udd1a\ud83c\udfff": " raised back of hand: dark skin tone",
    "\ud83e\udd1b\ud83c\udffb": " left-facing fist: light skin tone",
    "\ud83e\udd1b\ud83c\udffc": " left-facing fist: medium-light skin tone",
    "\ud83e\udd1b\ud83c\udffd": " left-facing fist: medium skin tone",
    "\ud83e\udd1b\ud83c\udffe": " left-facing fist: medium-dark skin tone",
    "\ud83e\udd1b\ud83c\udfff": " left-facing fist: dark skin tone",
    "\ud83e\udd1c\ud83c\udffb": " right-facing fist: light skin tone",
    "\ud83e\udd1c\ud83c\udffc": " right-facing fist: medium-light skin tone",
    "\ud83e\udd1c\ud83c\udffd": " right-facing fist: medium skin tone",
    "\ud83e\udd1c\ud83c\udffe": " right-facing fist: medium-dark skin tone",
    "\ud83e\udd1c\ud83c\udfff": " right-facing fist: dark skin tone",
    "\ud83e\udd1d\ud83c\udffb": " handshake: light skin tone",
    "\ud83e\udd1d\ud83c\udffc": " handshake: medium-light skin tone",
    "\ud83e\udd1d\ud83c\udffd": " handshake: medium skin tone",
    "\ud83e\udd1d\ud83c\udffe": " handshake: medium-dark skin tone",
    "\ud83e\udd1d\ud83c\udfff": " handshake: dark skin tone",
    "\ud83e\udd1e\ud83c\udffb": " crossed fingers: light skin tone",
    "\ud83e\udd1e\ud83c\udffc": " crossed fingers: medium-light skin tone",
    "\ud83e\udd1e\ud83c\udffd": " crossed fingers: medium skin tone",
    "\ud83e\udd1e\ud83c\udffe": " crossed fingers: medium-dark skin tone",
    "\ud83e\udd1e\ud83c\udfff": " crossed fingers: dark skin tone",
    "\ud83e\udd1f\ud83c\udffb": " love-you gesture: light skin tone",
    "\ud83e\udd1f\ud83c\udffc": " love-you gesture: medium-light skin tone",
    "\ud83e\udd1f\ud83c\udffd": " love-you gesture: medium skin tone",
    "\ud83e\udd1f\ud83c\udffe": " love-you gesture: medium-dark skin tone",
    "\ud83e\udd1f\ud83c\udfff": " love-you gesture: dark skin tone",
    "\ud83e\udd26\ud83c\udffb": " person facepalming: light skin tone",
    "\ud83e\udd26\ud83c\udffc": " person facepalming: medium-light skin tone",
    "\ud83e\udd26\ud83c\udffd": " person facepalming: medium skin tone",
    "\ud83e\udd26\ud83c\udffe": " person facepalming: medium-dark skin tone",
    "\ud83e\udd26\ud83c\udfff": " person facepalming: dark skin tone",
    "\ud83e\udd30\ud83c\udffb": " pregnant woman: light skin tone",
    "\ud83e\udd30\ud83c\udffc": " pregnant woman: medium-light skin tone",
    "\ud83e\udd30\ud83c\udffd": " pregnant woman: medium skin tone",
    "\ud83e\udd30\ud83c\udffe": " pregnant woman: medium-dark skin tone",
    "\ud83e\udd30\ud83c\udfff": " pregnant woman: dark skin tone",
    "\ud83e\udd31\ud83c\udffb": " breast-feeding: light skin tone",
    "\ud83e\udd31\ud83c\udffc": " breast-feeding: medium-light skin tone",
    "\ud83e\udd31\ud83c\udffd": " breast-feeding: medium skin tone",
    "\ud83e\udd31\ud83c\udffe": " breast-feeding: medium-dark skin tone",
    "\ud83e\udd31\ud83c\udfff": " breast-feeding: dark skin tone",
    "\ud83e\udd32\ud83c\udffb": " palms up together: light skin tone",
    "\ud83e\udd32\ud83c\udffc": " palms up together: medium-light skin tone",
    "\ud83e\udd32\ud83c\udffd": " palms up together: medium skin tone",
    "\ud83e\udd32\ud83c\udffe": " palms up together: medium-dark skin tone",
    "\ud83e\udd32\ud83c\udfff": " palms up together: dark skin tone",
    "\ud83e\udd33\ud83c\udffb": " selfie: light skin tone",
    "\ud83e\udd33\ud83c\udffc": " selfie: medium-light skin tone",
    "\ud83e\udd33\ud83c\udffd": " selfie: medium skin tone",
    "\ud83e\udd33\ud83c\udffe": " selfie: medium-dark skin tone",
    "\ud83e\udd33\ud83c\udfff": " selfie: dark skin tone",
    "\ud83e\udd34\ud83c\udffb": " prince: light skin tone",
    "\ud83e\udd34\ud83c\udffc": " prince: medium-light skin tone",
    "\ud83e\udd34\ud83c\udffd": " prince: medium skin tone",
    "\ud83e\udd34\ud83c\udffe": " prince: medium-dark skin tone",
    "\ud83e\udd34\ud83c\udfff": " prince: dark skin tone",
    "\ud83e\udd35\ud83c\udffb": " person in tuxedo: light skin tone",
    "\ud83e\udd35\ud83c\udffc": " person in tuxedo: medium-light skin tone",
    "\ud83e\udd35\ud83c\udffd": " person in tuxedo: medium skin tone",
    "\ud83e\udd35\ud83c\udffe": " person in tuxedo: medium-dark skin tone",
    "\ud83e\udd35\ud83c\udfff": " person in tuxedo: dark skin tone",
    "\ud83e\udd36\ud83c\udffb": " Mrs. Claus: light skin tone",
    "\ud83e\udd36\ud83c\udffc": " Mrs. Claus: medium-light skin tone",
    "\ud83e\udd36\ud83c\udffd": " Mrs. Claus: medium skin tone",
    "\ud83e\udd36\ud83c\udffe": " Mrs. Claus: medium-dark skin tone",
    "\ud83e\udd36\ud83c\udfff": " Mrs. Claus: dark skin tone",
    "\ud83e\udd37\ud83c\udffb": " person shrugging: light skin tone",
    "\ud83e\udd37\ud83c\udffc": " person shrugging: medium-light skin tone",
    "\ud83e\udd37\ud83c\udffd": " person shrugging: medium skin tone",
    "\ud83e\udd37\ud83c\udffe": " person shrugging: medium-dark skin tone",
    "\ud83e\udd37\ud83c\udfff": " person shrugging: dark skin tone",
    "\ud83e\udd38\ud83c\udffb": " person cartwheeling: light skin tone",
    "\ud83e\udd38\ud83c\udffc": " person cartwheeling: medium-light skin tone",
    "\ud83e\udd38\ud83c\udffd": " person cartwheeling: medium skin tone",
    "\ud83e\udd38\ud83c\udffe": " person cartwheeling: medium-dark skin tone",
    "\ud83e\udd38\ud83c\udfff": " person cartwheeling: dark skin tone",
    "\ud83e\udd39\ud83c\udffb": " person juggling: light skin tone",
    "\ud83e\udd39\ud83c\udffc": " person juggling: medium-light skin tone",
    "\ud83e\udd39\ud83c\udffd": " person juggling: medium skin tone",
    "\ud83e\udd39\ud83c\udffe": " person juggling: medium-dark skin tone",
    "\ud83e\udd39\ud83c\udfff": " person juggling: dark skin tone",
    "\ud83e\udd3d\ud83c\udffb": " person playing water polo: light skin tone",
    "\ud83e\udd3d\ud83c\udffc": " person playing water polo: medium-light skin tone",
    "\ud83e\udd3d\ud83c\udffd": " person playing water polo: medium skin tone",
    "\ud83e\udd3d\ud83c\udffe": " person playing water polo: medium-dark skin tone",
    "\ud83e\udd3d\ud83c\udfff": " person playing water polo: dark skin tone",
    "\ud83e\udd3e\ud83c\udffb": " person playing handball: light skin tone",
    "\ud83e\udd3e\ud83c\udffc": " person playing handball: medium-light skin tone",
    "\ud83e\udd3e\ud83c\udffd": " person playing handball: medium skin tone",
    "\ud83e\udd3e\ud83c\udffe": " person playing handball: medium-dark skin tone",
    "\ud83e\udd3e\ud83c\udfff": " person playing handball: dark skin tone",
    "\ud83e\udd77\ud83c\udffb": " ninja: light skin tone",
    "\ud83e\udd77\ud83c\udffc": " ninja: medium-light skin tone",
    "\ud83e\udd77\ud83c\udffd": " ninja: medium skin tone",
    "\ud83e\udd77\ud83c\udffe": " ninja: medium-dark skin tone",
    "\ud83e\udd77\ud83c\udfff": " ninja: dark skin tone",
    "\ud83e\uddb5\ud83c\udffb": " leg: light skin tone",
    "\ud83e\uddb5\ud83c\udffc": " leg: medium-light skin tone",
    "\ud83e\uddb5\ud83c\udffd": " leg: medium skin tone",
    "\ud83e\uddb5\ud83c\udffe": " leg: medium-dark skin tone",
    "\ud83e\uddb5\ud83c\udfff": " leg: dark skin tone",
    "\ud83e\uddb6\ud83c\udffb": " foot: light skin tone",
    "\ud83e\uddb6\ud83c\udffc": " foot: medium-light skin tone",
    "\ud83e\uddb6\ud83c\udffd": " foot: medium skin tone",
    "\ud83e\uddb6\ud83c\udffe": " foot: medium-dark skin tone",
    "\ud83e\uddb6\ud83c\udfff": " foot: dark skin tone",
    "\ud83e\uddb8\ud83c\udffb": " superhero: light skin tone",
    "\ud83e\uddb8\ud83c\udffc": " superhero: medium-light skin tone",
    "\ud83e\uddb8\ud83c\udffd": " superhero: medium skin tone",
    "\ud83e\uddb8\ud83c\udffe": " superhero: medium-dark skin tone",
    "\ud83e\uddb8\ud83c\udfff": " superhero: dark skin tone",
    "\ud83e\uddb9\ud83c\udffb": " supervillain: light skin tone",
    "\ud83e\uddb9\ud83c\udffc": " supervillain: medium-light skin tone",
    "\ud83e\uddb9\ud83c\udffd": " supervillain: medium skin tone",
    "\ud83e\uddb9\ud83c\udffe": " supervillain: medium-dark skin tone",
    "\ud83e\uddb9\ud83c\udfff": " supervillain: dark skin tone",
    "\ud83e\uddbb\ud83c\udffb": " ear with hearing aid: light skin tone",
    "\ud83e\uddbb\ud83c\udffc": " ear with hearing aid: medium-light skin tone",
    "\ud83e\uddbb\ud83c\udffd": " ear with hearing aid: medium skin tone",
    "\ud83e\uddbb\ud83c\udffe": " ear with hearing aid: medium-dark skin tone",
    "\ud83e\uddbb\ud83c\udfff": " ear with hearing aid: dark skin tone",
    "\ud83e\uddcd\ud83c\udffb": " person standing: light skin tone",
    "\ud83e\uddcd\ud83c\udffc": " person standing: medium-light skin tone",
    "\ud83e\uddcd\ud83c\udffd": " person standing: medium skin tone",
    "\ud83e\uddcd\ud83c\udffe": " person standing: medium-dark skin tone",
    "\ud83e\uddcd\ud83c\udfff": " person standing: dark skin tone",
    "\ud83e\uddce\ud83c\udffb": " person kneeling: light skin tone",
    "\ud83e\uddce\ud83c\udffc": " person kneeling: medium-light skin tone",
    "\ud83e\uddce\ud83c\udffd": " person kneeling: medium skin tone",
    "\ud83e\uddce\ud83c\udffe": " person kneeling: medium-dark skin tone",
    "\ud83e\uddce\ud83c\udfff": " person kneeling: dark skin tone",
    "\ud83e\uddcf\ud83c\udffb": " deaf person: light skin tone",
    "\ud83e\uddcf\ud83c\udffc": " deaf person: medium-light skin tone",
    "\ud83e\uddcf\ud83c\udffd": " deaf person: medium skin tone",
    "\ud83e\uddcf\ud83c\udffe": " deaf person: medium-dark skin tone",
    "\ud83e\uddcf\ud83c\udfff": " deaf person: dark skin tone",
    "\ud83e\uddd1\ud83c\udffb": " person: light skin tone",
    "\ud83e\uddd1\ud83c\udffc": " person: medium-light skin tone",
    "\ud83e\uddd1\ud83c\udffd": " person: medium skin tone",
    "\ud83e\uddd1\ud83c\udffe": " person: medium-dark skin tone",
    "\ud83e\uddd1\ud83c\udfff": " person: dark skin tone",
    "\ud83e\uddd2\ud83c\udffb": " child: light skin tone",
    "\ud83e\uddd2\ud83c\udffc": " child: medium-light skin tone",
    "\ud83e\uddd2\ud83c\udffd": " child: medium skin tone",
    "\ud83e\uddd2\ud83c\udffe": " child: medium-dark skin tone",
    "\ud83e\uddd2\ud83c\udfff": " child: dark skin tone",
    "\ud83e\uddd3\ud83c\udffb": " older person: light skin tone",
    "\ud83e\uddd3\ud83c\udffc": " older person: medium-light skin tone",
    "\ud83e\uddd3\ud83c\udffd": " older person: medium skin tone",
    "\ud83e\uddd3\ud83c\udffe": " older person: medium-dark skin tone",
    "\ud83e\uddd3\ud83c\udfff": " older person: dark skin tone",
    "\ud83e\uddd4\ud83c\udffb": " person: light skin tone, beard",
    "\ud83e\uddd4\ud83c\udffc": " person: medium-light skin tone, beard",
    "\ud83e\uddd4\ud83c\udffd": " person: medium skin tone, beard",
    "\ud83e\uddd4\ud83c\udffe": " person: medium-dark skin tone, beard",
    "\ud83e\uddd4\ud83c\udfff": " person: dark skin tone, beard",
    "\ud83e\uddd5\ud83c\udffb": " woman with headscarf: light skin tone",
    "\ud83e\uddd5\ud83c\udffc": " woman with headscarf: medium-light skin tone",
    "\ud83e\uddd5\ud83c\udffd": " woman with headscarf: medium skin tone",
    "\ud83e\uddd5\ud83c\udffe": " woman with headscarf: medium-dark skin tone",
    "\ud83e\uddd5\ud83c\udfff": " woman with headscarf: dark skin tone",
    "\ud83e\uddd6\ud83c\udffb": " person in steamy room: light skin tone",
    "\ud83e\uddd6\ud83c\udffc": " person in steamy room: medium-light skin tone",
    "\ud83e\uddd6\ud83c\udffd": " person in steamy room: medium skin tone",
    "\ud83e\uddd6\ud83c\udffe": " person in steamy room: medium-dark skin tone",
    "\ud83e\uddd6\ud83c\udfff": " person in steamy room: dark skin tone",
    "\ud83e\uddd7\ud83c\udffb": " person climbing: light skin tone",
    "\ud83e\uddd7\ud83c\udffc": " person climbing: medium-light skin tone",
    "\ud83e\uddd7\ud83c\udffd": " person climbing: medium skin tone",
    "\ud83e\uddd7\ud83c\udffe": " person climbing: medium-dark skin tone",
    "\ud83e\uddd7\ud83c\udfff": " person climbing: dark skin tone",
    "\ud83e\uddd8\ud83c\udffb": " person in lotus position: light skin tone",
    "\ud83e\uddd8\ud83c\udffc": " person in lotus position: medium-light skin tone",
    "\ud83e\uddd8\ud83c\udffd": " person in lotus position: medium skin tone",
    "\ud83e\uddd8\ud83c\udffe": " person in lotus position: medium-dark skin tone",
    "\ud83e\uddd8\ud83c\udfff": " person in lotus position: dark skin tone",
    "\ud83e\uddd9\ud83c\udffb": " mage: light skin tone",
    "\ud83e\uddd9\ud83c\udffc": " mage: medium-light skin tone",
    "\ud83e\uddd9\ud83c\udffd": " mage: medium skin tone",
    "\ud83e\uddd9\ud83c\udffe": " mage: medium-dark skin tone",
    "\ud83e\uddd9\ud83c\udfff": " mage: dark skin tone",
    "\ud83e\uddda\ud83c\udffb": " fairy: light skin tone",
    "\ud83e\uddda\ud83c\udffc": " fairy: medium-light skin tone",
    "\ud83e\uddda\ud83c\udffd": " fairy: medium skin tone",
    "\ud83e\uddda\ud83c\udffe": " fairy: medium-dark skin tone",
    "\ud83e\uddda\ud83c\udfff": " fairy: dark skin tone",
    "\ud83e\udddb\ud83c\udffb": " vampire: light skin tone",
    "\ud83e\udddb\ud83c\udffc": " vampire: medium-light skin tone",
    "\ud83e\udddb\ud83c\udffd": " vampire: medium skin tone",
    "\ud83e\udddb\ud83c\udffe": " vampire: medium-dark skin tone",
    "\ud83e\udddb\ud83c\udfff": " vampire: dark skin tone",
    "\ud83e\udddc\ud83c\udffb": " merperson: light skin tone",
    "\ud83e\udddc\ud83c\udffc": " merperson: medium-light skin tone",
    "\ud83e\udddc\ud83c\udffd": " merperson: medium skin tone",
    "\ud83e\udddc\ud83c\udffe": " merperson: medium-dark skin tone",
    "\ud83e\udddc\ud83c\udfff": " merperson: dark skin tone",
    "\ud83e\udddd\ud83c\udffb": " elf: light skin tone",
    "\ud83e\udddd\ud83c\udffc": " elf: medium-light skin tone",
    "\ud83e\udddd\ud83c\udffd": " elf: medium skin tone",
    "\ud83e\udddd\ud83c\udffe": " elf: medium-dark skin tone",
    "\ud83e\udddd\ud83c\udfff": " elf: dark skin tone",
    "\ud83e\udec3\ud83c\udffb": " pregnant man: light skin tone",
    "\ud83e\udec3\ud83c\udffc": " pregnant man: medium-light skin tone",
    "\ud83e\udec3\ud83c\udffd": " pregnant man: medium skin tone",
    "\ud83e\udec3\ud83c\udffe": " pregnant man: medium-dark skin tone",
    "\ud83e\udec3\ud83c\udfff": " pregnant man: dark skin tone",
    "\ud83e\udec4\ud83c\udffb": " pregnant person: light skin tone",
    "\ud83e\udec4\ud83c\udffc": " pregnant person: medium-light skin tone",
    "\ud83e\udec4\ud83c\udffd": " pregnant person: medium skin tone",
    "\ud83e\udec4\ud83c\udffe": " pregnant person: medium-dark skin tone",
    "\ud83e\udec4\ud83c\udfff": " pregnant person: dark skin tone",
    "\ud83e\udec5\ud83c\udffb": " person with crown: light skin tone",
    "\ud83e\udec5\ud83c\udffc": " person with crown: medium-light skin tone",
    "\ud83e\udec5\ud83c\udffd": " person with crown: medium skin tone",
    "\ud83e\udec5\ud83c\udffe": " person with crown: medium-dark skin tone",
    "\ud83e\udec5\ud83c\udfff": " person with crown: dark skin tone",
    "\ud83e\udef0\ud83c\udffb": " hand with index finger and thumb crossed: light skin tone",
    "\ud83e\udef0\ud83c\udffc": " hand with index finger and thumb crossed: medium-light skin tone",
    "\ud83e\udef0\ud83c\udffd": " hand with index finger and thumb crossed: medium skin tone",
    "\ud83e\udef0\ud83c\udffe": " hand with index finger and thumb crossed: medium-dark skin tone",
    "\ud83e\udef0\ud83c\udfff": " hand with index finger and thumb crossed: dark skin tone",
    "\ud83e\udef1\ud83c\udffb": " rightwards hand: light skin tone",
    "\ud83e\udef1\ud83c\udffc": " rightwards hand: medium-light skin tone",
    "\ud83e\udef1\ud83c\udffd": " rightwards hand: medium skin tone",
    "\ud83e\udef1\ud83c\udffe": " rightwards hand: medium-dark skin tone",
    "\ud83e\udef1\ud83c\udfff": " rightwards hand: dark skin tone",
    "\ud83e\udef2\ud83c\udffb": " leftwards hand: light skin tone",
    "\ud83e\udef2\ud83c\udffc": " leftwards hand: medium-light skin tone",
    "\ud83e\udef2\ud83c\udffd": " leftwards hand: medium skin tone",
    "\ud83e\udef2\ud83c\udffe": " leftwards hand: medium-dark skin tone",
    "\ud83e\udef2\ud83c\udfff": " leftwards hand: dark skin tone",
    "\ud83e\udef3\ud83c\udffb": " palm down hand: light skin tone",
    "\ud83e\udef3\ud83c\udffc": " palm down hand: medium-light skin tone",
    "\ud83e\udef3\ud83c\udffd": " palm down hand: medium skin tone",
    "\ud83e\udef3\ud83c\udffe": " palm down hand: medium-dark skin tone",
    "\ud83e\udef3\ud83c\udfff": " palm down hand: dark skin tone",
    "\ud83e\udef4\ud83c\udffb": " palm up hand: light skin tone",
    "\ud83e\udef4\ud83c\udffc": " palm up hand: medium-light skin tone",
    "\ud83e\udef4\ud83c\udffd": " palm up hand: medium skin tone",
    "\ud83e\udef4\ud83c\udffe": " palm up hand: medium-dark skin tone",
    "\ud83e\udef4\ud83c\udfff": " palm up hand: dark skin tone",
    "\ud83e\udef5\ud83c\udffb": " index pointing at the viewer: light skin tone",
    "\ud83e\udef5\ud83c\udffc": " index pointing at the viewer: medium-light skin tone",
    "\ud83e\udef5\ud83c\udffd": " index pointing at the viewer: medium skin tone",
    "\ud83e\udef5\ud83c\udffe": " index pointing at the viewer: medium-dark skin tone",
    "\ud83e\udef5\ud83c\udfff": " index pointing at the viewer: dark skin tone",
    "\ud83e\udef6\ud83c\udffb": " heart hands: light skin tone",
    "\ud83e\udef6\ud83c\udffc": " heart hands: medium-light skin tone",
    "\ud83e\udef6\ud83c\udffd": " heart hands: medium skin tone",
    "\ud83e\udef6\ud83c\udffe": " heart hands: medium-dark skin tone",
    "\ud83e\udef6\ud83c\udfff": " heart hands: dark skin tone",
    "\ud83e\udef7\ud83c\udffb": " leftwards pushing hand: light skin tone",
    "\ud83e\udef7\ud83c\udffc": " leftwards pushing hand: medium-light skin tone",
    "\ud83e\udef7\ud83c\udffd": " leftwards pushing hand: medium skin tone",
    "\ud83e\udef7\ud83c\udffe": " leftwards pushing hand: medium-dark skin tone",
    "\ud83e\udef7\ud83c\udfff": " leftwards pushing hand: dark skin tone",
    "\ud83e\udef8\ud83c\udffb": " rightwards pushing hand: light skin tone",
    "\ud83e\udef8\ud83c\udffc": " rightwards pushing hand: medium-light skin tone",
    "\ud83e\udef8\ud83c\udffd": " rightwards pushing hand: medium skin tone",
    "\ud83e\udef8\ud83c\udffe": " rightwards pushing hand: medium-dark skin tone",
    "\ud83e\udef8\ud83c\udfff": " rightwards pushing hand: dark skin tone"
}